import { expect, test } from "@playwright/test";
import { createSeedState } from "../../src/domain";
import { createPersonNeed } from "../../src/glyphs";

test.setTimeout(90000);
test("person symbols have captions in the tree, report charts, kinship and exports", async ({ page }, info) => {
  const state = createSeedState(), errors: string[] = [];
  state.people[0].accessNeeds = [createPersonNeed("cerebral-palsy", "Recorded by the person"), createPersonNeed("captions", "Written transcript")];
  state.relationships.find(r => r.type === "spouse")!.status = "divorced";
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.evaluate(state => localStorage.setItem("kinforge-demo-v1", JSON.stringify(state)), state);
  await page.reload(); await page.getByRole("button", { name: "Continue as guest" }).click();
  const alex = page.locator('.react-flow__node[data-id="person_alex"]');
  await expect.poll(async () => await alex.locator(".glyph-caption").allTextContents()).toEqual(expect.arrayContaining(["Male", "Divorce", "Father"]));
  await page.getByLabel("Show private annotations", { exact: true }).check();
  await expect.poll(async () => await alex.locator(".glyph-caption").allTextContents()).toEqual(expect.arrayContaining(["Male", "Divorce", "Father", "Cerebral palsy (CP)", "Captions"]));
  const captionsBelow = await alex.locator(".captioned-glyph").evaluateAll(nodes => nodes.every(node => node.querySelector(".glyph-caption")!.getBoundingClientRect().top >= node.querySelector("svg")!.getBoundingClientRect().bottom));
  expect(captionsBelow).toBe(true);
  expect(await alex.locator(".person-symbols").evaluate(area => [...area.querySelectorAll(".glyph-caption")].every(caption => caption.getBoundingClientRect().bottom <= area.getBoundingClientRect().bottom))).toBe(true);
  await alex.locator(".person-symbols").focus(); await page.keyboard.press("ArrowRight");
  await expect.poll(() => alex.locator(".person-symbols").evaluate(area => area.scrollLeft)).toBeGreaterThan(0);
  await page.screenshot({ path: info.outputPath("tree-with-captioned-symbols.png"), fullPage: true });

  await page.getByRole("link", { name: "Reports", exact: true }).click();
  const draft = page.getByRole("textbox", { name: "Report draft", exact: true });
  await page.getByLabel("Report type", { exact: true }).selectOption("Genogram");
  await page.getByRole("button", { name: "Generate Editable Draft", exact: true }).click();
  await expect(draft).toContainText("Gender recorded as male");
  await expect(draft).toContainText("Recorded divorce event");
  await expect(draft).not.toContainText("Recorded by the person");
  await expect(draft.locator('img[title="report-line"]')).not.toHaveCount(0);
  await page.getByLabel("Include private people and annotations", { exact: true }).check();
  await page.getByRole("button", { name: "Generate Editable Draft", exact: true }).click();
  await expect(draft).toContainText("Recorded by the person");
  await page.emulateMedia({ media: "print" });
  await expect(page.getByLabel("Draft name", { exact: true })).not.toBeVisible();
  await page.emulateMedia({ media: "screen" });
  await expect(draft).toContainText("does not specify movement, communication or cognitive abilities");
  const symbols = draft.locator(".report-symbol");
  expect(await symbols.count()).toBeGreaterThan(6);
  expect(await symbols.evaluateAll(nodes => nodes.every(node => {
    const image = node.querySelector("img")!, caption = node.querySelector("p")!;
    return image.complete && image.naturalWidth > 0 && caption.textContent?.trim() && caption.getBoundingClientRect().top >= image.getBoundingClientRect().bottom;
  }))).toBe(true);
  await draft.getByRole("heading", { name: "Symbols for Alex Chang", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("report-symbol-meanings.png"), fullPage: true });
  const rtfDownload = page.waitForEvent("download"); await page.getByRole("button", { name: "RTF", exact: true }).click();
  await (await rtfDownload).saveAs(info.outputPath("labelled-genogram.rtf"));

  await page.getByLabel("Report type", { exact: true }).selectOption("Kinship Report");
  await page.getByLabel("Reference person", { exact: true }).selectOption("person_june");
  await page.getByLabel("Compare with", { exact: true }).selectOption("person_alex");
  await page.getByRole("button", { name: "Generate Editable Draft", exact: true }).click();
  await expect(draft).toContainText("Symbols for Alex Chang");
  await expect(draft).toContainText("Cerebral palsy (CP)");
  await expect(draft).toContainText("Once removed = 1 generation apart");
  await page.getByLabel("Draft name", { exact: true }).fill("Kinship with explained symbols");
  await page.reload(); await expect(page.getByLabel("Draft name", { exact: true })).toHaveValue("Kinship with explained symbols");
  await expect(draft).toContainText("Recorded by the person");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await draft.getByRole("heading", { name: "Symbols for Alex Chang", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("kinship-symbols-mobile.png"), fullPage: true });
  const before = await page.getByLabel("Saved drafts", { exact: true }).locator("option").count();
  await page.getByRole("button", { name: "Delete selected draft" }).click();
  await page.getByRole("dialog", { name: "Delete report draft?", exact: true }).getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByLabel("Saved drafts", { exact: true }).locator("option")).toHaveCount(before);
  await page.getByRole("button", { name: "Delete selected draft" }).click();
  await page.getByRole("dialog", { name: "Delete report draft?", exact: true }).getByRole("button", { name: "Delete", exact: true }).click();
  await expect(page.getByLabel("Saved drafts", { exact: true }).locator("option")).toHaveCount(before - 1);
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("kinforge-demo-v1")!).people.length)).toBe(4);
  expect(errors).toEqual([]);
});
