export type ValidationTarget = {
  target: string;
  validates: string;
  tests: string[];
};

export const VALIDATION_TARGETS: ValidationTarget[] = [
  { target: "auth-flow", validates: "server-verified accounts, protected sessions, recovery codes, account isolation and sign-out", tests: ["tests/cloud-api.test.mjs", "tests/native-cloud.mjs"] },
  { target: "cloud-sync", validates: "automatic account library sync, existing data transfer, offline recovery, conflict resolution, permissions and responsive navigation", tests: ["src/cloudMerge.test.ts", "tests/cloud-api.test.mjs", "tests/browser/cloud-sync.spec.ts", "tests/native-cloud.mjs"] },
  { target: "brand-presence", validates: "product branding in the shell and releases", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "build-web", validates: "production browser build", tests: ["npm run build"] },
  { target: "build-webapp", validates: "installable offline webapp bundle", tests: ["npm run build", "tests/browser/workspace.spec.ts"] },
  { target: "build-website", validates: "standalone product website bundle", tests: ["npm run build:website"] },
  { target: "chart-config", validates: "chart style, placement, pagination and editable object controls", tests: ["src/reportContentOptions.test.ts", "tests/browser/report-editor-parity.spec.ts"] },
  { target: "chart-types", validates: "tree, fan, relationship, genogram, sociogram, timeline, statistics and chart diagrams", tests: ["src/reportCatalog.test.ts", "src/treeGraph.test.ts", "tests/browser/reports.spec.ts"] },
  { target: "changes", validates: "change history, undo/redo stacks and persisted edit audit behavior", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts", "tests/browser/maintenance.spec.ts"] },
  { target: "citation-style", validates: "citation text and source presentation in reports and charts", tests: ["src/reportCatalog.test.ts", "src/reportDocument.test.ts", "tests/browser/reports.spec.ts"] },
  { target: "collections", validates: "books, collections, nested subcollections and associated trees", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "custom-data", validates: "custom facts, labels, templates, event fields and user-defined profile data", tests: ["src/kinforge.test.ts", "src/reportContentOptions.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "dna", validates: "DNA matches, genetic groups, chromosome segments, clusters, cM and relationship estimates", tests: ["src/kinforge.test.ts"] },
  { target: "duplicates", validates: "duplicate detection and reviewed merge behavior", tests: ["src/kinforge.test.ts", "src/maintenance.test.ts"] },
  { target: "families", validates: "family groups, unions, children and family-source links", tests: ["src/treeGraph.test.ts", "src/familyLines.test.ts", "tests/browser/generations.spec.ts"] },
  { target: "feature-matrix", validates: "combined MyHeritage, Ancestry, MacFamilyTree and best-of capability coverage", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "gedcom", validates: "GEDCOM 5.5.1 and 7 import/export, encodings, line endings and media/note options", tests: ["src/kinforge.test.ts", "src/reportImportedDates.test.ts"] },
  { target: "gedcom-merge", validates: "GEDCOM append and merge review for identical people, families and facts", tests: ["src/kinforge.test.ts"] },
  { target: "government-details", validates: "government events, protective services, custody, criminal and sensitive child details", tests: ["src/kinforge.test.ts", "src/reportCatalog.test.ts", "tests/browser/report-parentage.spec.ts"] },
  { target: "ideas-parity", validates: "exact Ideas.md wording and parity rows", tests: ["src/kinforge.test.ts", "src/requirements.test.ts"] },
  { target: "languages", validates: "supported language list and localized narrative/report generation", tests: ["src/kinforge.test.ts", "src/reportNarrativeLocales.test.ts"] },
  { target: "labels", validates: "user-defined labels on people, filters and reports", tests: ["src/kinforge.test.ts", "src/reportContentOptions.test.ts"] },
  { target: "list-types", validates: "all requested list outputs and list-specific filters", tests: ["src/kinforge.test.ts", "src/reportCatalog.test.ts", "src/reportContentOptions.test.ts"] },
  { target: "maintenance", validates: "search/replace, date, name, cleanup, repair, media and evidence maintenance", tests: ["src/maintenance.test.ts", "tests/browser/maintenance.spec.ts"] },
  { target: "media-assignments", validates: "media assigned to people, families, sources, places and events", tests: ["src/reportRich.test.ts", "src/reportContentOptions.test.ts", "tests/browser/report-rich.spec.ts"] },
  { target: "media-tools", validates: "picture rotation/crop state, enhancement flags, repair flags, tagging, stories and transcripts", tests: ["src/reportRich.test.ts", "tests/browser/report-rich.spec.ts", "tests/browser/glyphs.spec.ts"] },
  { target: "media-types", validates: "pictures, videos, audio, PDFs/documents and websites as media records", tests: ["src/kinforge.test.ts", "src/reportRich.test.ts", "tests/browser/report-rich.spec.ts"] },
  { target: "ordinance-list", validates: "LDS ordinance facts, lists, citations and privacy handling", tests: ["src/reportContentOptions.test.ts", "src/reportCatalog.test.ts"] },
  { target: "package-config", validates: "desktop packaging metadata and versioned app configuration", tests: ["tests/native-smoke.mjs", "npm run build"] },
  { target: "package-mac", validates: "Apple Silicon and Intel DMG/ZIP/PKG artifacts", tests: ["electron-builder --mac", "hdiutil verify"] },
  { target: "package-win", validates: "Windows setup and portable executable configuration", tests: ["electron-builder --win"] },
  { target: "person-create", validates: "person creation, relatives, unlimited-growth path and persistence", tests: ["src/treeGraph.test.ts", "tests/browser/workspace.spec.ts", "tests/browser/generations.spec.ts"] },
  { target: "person-update", validates: "classical person forms and profile editing", tests: ["tests/browser/workspace.spec.ts", "src/reportDocument.test.ts"] },
  { target: "place-levels", validates: "administrative place levels and mapped place details", tests: ["src/reportRich.test.ts", "src/reportCatalog.test.ts"] },
  { target: "place-templates", validates: "configurable place templates and address/POI fields", tests: ["src/reportRich.test.ts", "src/reportCatalog.test.ts"] },
  { target: "places", validates: "place records, coordinates, map reports, globe/statistics views and POIs", tests: ["src/reportRich.test.ts", "src/reportCatalog.test.ts", "tests/browser/report-rich.spec.ts"] },
  { target: "plausibility", validates: "tree checker, date/relationship plausibility and issue reporting", tests: ["src/kinforge.test.ts", "src/reportParity.test.ts", "src/maintenance.test.ts"] },
  { target: "predefined-events", validates: "20+ predefined event types and glyph meanings", tests: ["src/kinforge.test.ts", "src/glyphs.test.ts"] },
  { target: "predefined-facts", validates: "20+ predefined fact types and custom fact handling", tests: ["src/kinforge.test.ts", "src/reportContentOptions.test.ts"] },
  { target: "privacy-export", validates: "private/living-person filtering in GEDCOM, reports, web and backups", tests: ["src/kinforge.test.ts", "src/reportRich.test.ts", "src/reportDocument.test.ts"] },
  { target: "quiz", validates: "family quiz dashboard feature path", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "records", validates: "historical record collections, citation, transcription and person links", tests: ["src/localResearch.test.ts", "src/reportRich.test.ts", "tests/browser/independence.spec.ts"] },
  { target: "report-types", validates: "all requested reports, diagrams, portraits, kinship and family-book outputs", tests: ["src/reportCatalog.test.ts", "src/reportParity.test.ts", "src/reportDocument.test.ts", "tests/browser/reports.spec.ts"] },
  { target: "reports-exports", validates: "editable drafts, PDF, fillable PDF, RTF, CSV, text, print and book exports", tests: ["src/reportPdfExports.test.ts", "src/reportDocument.test.ts", "tests/browser/reportPdfExports.spec.ts", "tests/browser/report-editor-parity.spec.ts"] },
  { target: "research-links", validates: "research launcher, FamilySearch-ready flow, Wikipedia/place lookup and local evidence review", tests: ["src/localResearch.test.ts", "tests/browser/independence.spec.ts"] },
  { target: "research-questions", validates: "autogenerated research questions, hints, theories and next-step tasks", tests: ["src/kinforge.test.ts", "src/maintenance.test.ts"] },
  { target: "research-site-count", validates: "about twenty genealogy website search targets", tests: ["src/kinforge.test.ts"] },
  { target: "seed-state", validates: "sample tree, starter records and data libraries", tests: ["src/kinforge.test.ts"] },
  { target: "smart-filters", validates: "people filters, tree checker filters and DNA/evidence review groups", tests: ["src/kinforge.test.ts", "src/reportContentOptions.test.ts"] },
  { target: "source-fields", validates: "source template fields and citation ownership", tests: ["src/kinforge.test.ts", "src/localResearch.test.ts", "src/reportCatalog.test.ts"] },
  { target: "source-quality", validates: "source discipline, claims without citations and evidence quality scoring", tests: ["src/maintenance.test.ts", "src/reportCatalog.test.ts"] },
  { target: "source-template-count", validates: "100+ predefined source templates", tests: ["src/kinforge.test.ts"] },
  { target: "source-templates", validates: "source template editor and reusable source records", tests: ["src/kinforge.test.ts", "src/localResearch.test.ts"] },
  { target: "todos", validates: "to-do lists, generated evidence tasks and task filters", tests: ["src/maintenance.test.ts", "src/reportContentOptions.test.ts", "tests/browser/maintenance.spec.ts"] },
  { target: "tree-author", validates: "family-tree author metadata", tests: ["src/kinforge.test.ts", "tests/browser/report-editor-parity.spec.ts"] },
  { target: "tree-create", validates: "multiple tree creation, switching and isolation", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "tree-edit", validates: "interactive tree editing, relatives, undo/redo, handles and relationship labels", tests: ["src/treeGraph.test.ts", "tests/browser/workspace.spec.ts", "tests/browser/generations.spec.ts"] },
  { target: "tree-view", validates: "virtual tree, generations, siblings, descendants, minimap, panning and zoom", tests: ["src/treeGraph.test.ts", "src/treeCentering.test.ts", "tests/browser/generations.spec.ts"] },
  { target: "virtual-tree", validates: "Virtual Tree view with dynamic family chart layout and navigation", tests: ["src/treeGraph.test.ts", "tests/browser/workspace.spec.ts", "tests/browser/generations.spec.ts"] },
  { target: "virtual-globe", validates: "Virtual Globe/place map projection and geographic reports", tests: ["src/reportRich.test.ts", "tests/browser/report-rich.spec.ts"] },
  { target: "statistic-maps", validates: "statistic maps and geographic distribution outputs", tests: ["src/reportCatalog.test.ts", "src/reportRich.test.ts"] },
  { target: "gallery", validates: "gallery views and media cards for people and albums", tests: ["src/reportRich.test.ts", "tests/browser/report-rich.spec.ts"] },
  { target: "family-quiz", validates: "Family Quiz dashboard card and family-relationship question workflow", tests: ["src/kinforge.test.ts", "tests/browser/workspace.spec.ts"] },
  { target: "website-export", validates: "static website/family-site export and invitation sharing", tests: ["tests/browser/report-editor-parity.spec.ts", "tests/browser/publish.spec.ts"] }
];

export const validationByTarget = new Map(VALIDATION_TARGETS.map(entry => [entry.target, entry]));
