import {
  Accessibility, Armchair, ArrowLeftRight, Award, Baby, BatteryMedium, Brain, BrainCircuit, BrainCog, BriefcaseBusiness, Building2, CalendarDays,
  Captions, CircleHelp, Clock3, Cross, Droplets, Ear, EarOff, Eye, EyeOff, FileCheck2, FileText,
  FileX2, Flag, Flower2, Gem, GraduationCap, Hand, HandHeart, HeartCrack,
  HeartHandshake, HeartPulse, House, HousePlus, Keyboard, Landmark, Languages, Link2,
  ListChecks, LockKeyhole, LogIn, LogOut, MapPin, Medal, MessageSquareText, MessageCircleOff, Move, PersonStanding,
  Footprints, Glasses, GitBranch, Minus, Pause, ScrollText,
  Plane, Plus, RotateCcw, Route, Scale, ShieldCheck, Speech, Star, Sun, SunDim, TestTube2, Type, Unlink, Users,
  VolumeX, Diamond, createLucideIcon, type LucideIcon
} from "lucide-react";
import { makeId, type PersonNeed } from "./domain";
import { meaningFor } from "./terms";

export type GlyphGroup = "Person" | "Relationships" | "Life events" | "Disabilities" | "Access needs" | "Record status";
export type GlyphDefinition = { id: string; label: string; group: GlyphGroup; icon: LucideIcon; modifier?: LucideIcon; meaning: string; eventType?: string; aliases?: string[] };

const event = (id: string, label: string, icon: LucideIcon, group: GlyphGroup = "Life events", meaning = `Recorded ${label.toLowerCase()} event.`, aliases: string[] = []): GlyphDefinition => ({ id, label, icon, group, meaning, eventType: label, aliases });
const protectionEvent = (id: string, label: string, icon: LucideIcon, group: GlyphGroup = "Life events", modifier?: LucideIcon): GlyphDefinition => ({ ...event(id, label, icon, group, meaningFor(label)), modifier });
const need = (id: string, label: string, icon: LucideIcon, meaning: string): GlyphDefinition => ({ id, label, icon, meaning, group: "Access needs" });
const disability = (id: string, label: string, icon: LucideIcon, meaning: string, aliases: string[] = [], modifier?: LucideIcon): GlyphDefinition => ({ id, label, icon, modifier, meaning, aliases, group: "Disabilities" });

// These standard person symbols are not included in the installed Lucide version.
const Male = createLucideIcon("Male", [["circle", { cx: "9", cy: "15", r: "6", key: "circle" }], ["path", { d: "M13 11 21 3M15 3h6v6", key: "arrow" }]]);
const Female = createLucideIcon("Female", [["circle", { cx: "12", cy: "8", r: "6", key: "circle" }], ["path", { d: "M12 14v8M8 18h8", key: "cross" }]]);
const Nonbinary = createLucideIcon("Nonbinary", [["circle", { cx: "12", cy: "14", r: "6", key: "circle" }], ["path", { d: "M12 8V2M8 3l8 4M8 7l8-4", key: "rays" }]]);

export const GLYPHS: GlyphDefinition[] = [
  { id: "gender-male", label: "Male", group: "Person", icon: Male, meaning: "Gender recorded as male; not a statement of sex assigned at birth." },
  { id: "gender-female", label: "Female", group: "Person", icon: Female, meaning: "Gender recorded as female; not a statement of sex assigned at birth." },
  { id: "gender-nonbinary", label: "Nonbinary", group: "Person", icon: Nonbinary, meaning: "Gender recorded as nonbinary; the symbol does not imply a particular transition history." },
  { id: "gender-unknown", label: "Not recorded", group: "Person", icon: Diamond, meaning: "Gender has not been recorded. This is not a gender identity." },
  { id: "identity-pronouns", label: "Pronouns", group: "Person", icon: Type, meaning: "Pronouns are recorded from the person's own wording or a source; they are not inferred from gender markers." },
  { id: "identity-gender", label: "Gender identity", group: "Person", icon: Nonbinary, meaning: "A self-described gender identity or source wording. It does not imply a specific medical, transition, or legal history." },
  { id: "identity-sexuality", label: "Sexual orientation", group: "Person", icon: HeartPulse, meaning: "A recorded sexual orientation label. KinForge does not infer this from partners or relationship history." },
  { id: "identity-romantic", label: "Romantic orientation", group: "Person", icon: HeartHandshake, meaning: "A recorded romantic orientation label. It may differ from sexual orientation." },
  { id: "identity-relationship-orientation", label: "Relationship orientation", group: "Person", icon: Users, meaning: "A recorded relationship style such as monogamous, polyamorous, ambiamorous or self-described wording." },
  event("engagement", "Engagement", Gem, "Relationships"),
  event("engagement-ended", "Engagement Ended", HeartCrack, "Relationships", "An engagement was recorded as ending; this does not imply a divorce."),
  event("betrothal", "Betrothal", Gem, "Relationships", "A recorded promise or agreement to marry."),
  event("relationship-started", "Relationship Started", HeartHandshake, "Relationships"),
  event("dating-started", "Dating Started", HeartPulse, "Relationships"),
  event("courtship-started", "Courtship Started", Flower2, "Relationships"),
  event("relationship-milestone", "Relationship Milestone", Star, "Relationships"),
  event("breakup", "Breakup", HeartCrack, "Relationships", "A recorded end to a relationship; it does not establish a legal divorce."),
  event("partner-breakup", "Partner Breakup", Unlink, "Relationships", "A recorded breakup with a partner; the person's notes describe the circumstances."),
  event("reconciliation", "Reconciliation", RotateCcw, "Relationships", "A recorded reconciliation; it does not automatically change legal relationship status."),
  event("cohabitation-started", "Cohabitation Started", HousePlus, "Relationships", "People are recorded as beginning to live together."),
  event("cohabitation-ended", "Cohabitation Ended", LogOut, "Relationships", "People are recorded as no longer living together; this does not by itself mean a breakup."),
  event("commitment-ceremony", "Commitment Ceremony", HeartHandshake, "Relationships", "A recorded commitment ceremony; legal marriage status is recorded separately."),
  event("civil-partnership", "Civil Partnership", FileCheck2, "Relationships"),
  event("domestic-partnership", "Domestic Partnership", House, "Relationships"),
  event("polycule-joined", "Polycule Joined", Users, "Relationships", "A recorded addition to a connected group of relationships; individual connections are recorded separately."),
  event("polycule-left", "Polycule Left", LogOut, "Relationships", "A person is recorded as leaving a connected relationship group."),
  event("metamour-link", "Metamour Link", GitBranch, "Relationships", "A recorded connection with a partner's other partner; it does not imply a romantic connection between the two people."),
  event("queerplatonic-partnership", "Queerplatonic Partnership", HeartHandshake, "Relationships", "A queerplatonic partnership recorded in the people's own terms."),
  event("relationship-agreement", "Relationship Agreement", ScrollText, "Relationships"),
  event("relationship-status-change", "Relationship Status Change", ArrowLeftRight, "Relationships"),
  event("marriage", "Marriage", Link2, "Relationships"),
  event("marriage-banns", "Marriage Banns", FileText, "Relationships"),
  event("marriage-license", "Marriage License", FileCheck2, "Relationships"),
  event("partnership", "Partnership", HeartHandshake, "Relationships"),
  event("civil-union", "Civil Union", HeartHandshake, "Relationships"),
  event("separation", "Separation", HeartCrack, "Relationships", "Recorded separation; not an assertion of divorce or conflict."),
  event("trial-separation", "Trial Separation", Pause, "Relationships", "A recorded trial separation; it does not establish a divorce."),
  event("legal-separation", "Legal Separation", Scale, "Relationships", "A separation recorded as legal; source documents supply the jurisdiction and details."),
  event("divorce-filing", "Divorce Filing", FileText, "Relationships", "Recorded divorce filing; not the same thing as a completed divorce."),
  event("divorce-decree", "Divorce Decree", FileCheck2, "Relationships", "A recorded divorce decree; its date and source belong in the event details."),
  event("divorce", "Divorce", Unlink, "Relationships", "Recorded divorce event; does not infer a legal outcome from other facts."),
  event("annulment", "Annulment", FileX2, "Relationships", "Recorded annulment event, distinct from separation and divorce."),
  event("annulment-filing", "Annulment Filing", FileText, "Relationships", "A recorded application for annulment; this does not mean the application was granted."),
  event("adoption", "Adoption", HousePlus, "Relationships"),
  event("guardianship", "Guardianship", ShieldCheck, "Relationships"),
  event("foster-care", "Foster Care", HandHeart, "Relationships"),
  event("child-custody", "Child Custody", ShieldCheck, "Relationships"),
  protectionEvent("custody-removal", "Custody Removal", ShieldCheck, "Relationships", Minus),
  protectionEvent("custody-change", "Custody Change", ShieldCheck, "Relationships", ArrowLeftRight),
  protectionEvent("custody-restoration", "Custody Restoration", ShieldCheck, "Relationships", RotateCcw),
  protectionEvent("foster-placement", "Foster Placement", HandHeart, "Relationships", Plus),
  protectionEvent("foster-placement-end", "Foster Placement End", HandHeart, "Relationships", Minus),
  { id: "relationship-parent", label: "Parent", group: "Relationships", icon: GitBranch, meaning: "A recorded parent relationship. Parentage details describe biological, adoptive, foster, step or other recorded roles when supplied." },
  { id: "relationship-child", label: "Child", group: "Relationships", icon: GitBranch, meaning: "A recorded child relationship. This does not infer parentage type unless the relationship records it." },
  { id: "relationship-sibling", label: "Sibling", group: "Relationships", icon: Users, meaning: "A recorded sibling relationship. It may be biological, half, step, adoptive or user-defined according to the recorded details." },
  { id: "relationship-spouse", label: "Spouse", group: "Relationships", icon: Link2, meaning: "A recorded spouse relationship." },
  { id: "relationship-partner", label: "Partner", group: "Relationships", icon: HeartHandshake, meaning: "A recorded partner relationship that is not necessarily a marriage." },
  { id: "relationship-guardian", label: "Guardian", group: "Relationships", icon: ShieldCheck, meaning: "A recorded guardian relationship." },
  { id: "relationship-ward", label: "Ward", group: "Relationships", icon: HandHeart, meaning: "A recorded ward relationship connected to a guardian." },
  { id: "relationship-immediate-family", label: "Immediate family", group: "Relationships", icon: Users, meaning: "A close family relationship such as a parent, child, sibling, spouse or partner." },
  { id: "relationship-extended-family", label: "Extended family", group: "Relationships", icon: GitBranch, meaning: "A wider family relationship outside the immediate household or nuclear family." },
  { id: "relationship-cousin", label: "Cousin", group: "Relationships", icon: GitBranch, meaning: "A cousin relationship. Cousin degree and removal are explained in kinship reports from the recorded path." },
  { id: "relationship-in-law", label: "In-law", group: "Relationships", icon: HeartHandshake, meaning: "A relationship connected through marriage, partnership, civil union or another recorded family bond." },
  { id: "relationship-cousin-in-law", label: "Cousin-in-law", group: "Relationships", icon: GitBranch, modifier: HeartHandshake, meaning: "A cousin relationship connected through a spouse, partner or in-law line rather than a direct bloodline." },
  { id: "relationship-biological", label: "Biological parentage", group: "Relationships", icon: Baby, meaning: "The parent-child link is recorded as biological. KinForge does not infer this from names, photos or gender." },
  { id: "relationship-adopted", label: "Adopted or adoptive parentage", group: "Relationships", icon: HousePlus, meaning: "The parent-child link is recorded as adoptive or adopted." },
  { id: "relationship-foster", label: "Foster parentage", group: "Relationships", icon: HandHeart, meaning: "The parent-child link is recorded as foster care or foster parentage." },
  { id: "relationship-step", label: "Step parentage", group: "Relationships", icon: GitBranch, meaning: "The parent-child link is recorded as step parentage." },
  { id: "single-parent", label: "Single parent", group: "Relationships", icon: PersonStanding, modifier: Baby, meaning: "This person is recorded as the only linked parent for at least one child in this tree." },
  { id: "single-mom", label: "Single mom", group: "Relationships", icon: Female, modifier: Baby, meaning: "This person is recorded as the only linked parent for at least one child and has gender recorded as female." },
  { id: "single-dad", label: "Single dad", group: "Relationships", icon: Male, modifier: Baby, meaning: "This person is recorded as the only linked parent for at least one child and has gender recorded as male." },
  event("birth", "Birth", Baby),
  event("naming", "Naming", Star),
  event("baptism", "Baptism", Droplets),
  event("christening", "Christening", Droplets),
  event("blessing", "Blessing", HeartPulse),
  event("residence", "Residence", MapPin),
  event("address-change", "Address Change", Route),
  event("education", "Education", GraduationCap),
  event("graduation", "Graduation", GraduationCap),
  event("occupation", "Occupation", BriefcaseBusiness),
  event("employment-start", "Employment Start", BriefcaseBusiness),
  event("employment-end", "Employment End", BriefcaseBusiness),
  event("work-contract-signed", "Work Contract Signed", FileCheck2),
  event("employment-contract", "Employment Contract", ScrollText),
  event("company-joined", "Company Joined", LogIn),
  event("company-left", "Company Left", LogOut),
  event("promotion", "Promotion", Award),
  event("workplace-accommodation", "Workplace Accommodation", Accessibility),
  event("work-transfer", "Work Transfer", ArrowLeftRight),
  event("freelance-contract", "Freelance Contract", BriefcaseBusiness),
  event("retirement", "Retirement", Armchair),
  event("immigration", "Immigration", Plane),
  event("emigration", "Emigration", Plane),
  event("naturalisation", "Naturalisation", Flag, "Life events", "Recorded naturalisation or naturalization event.", ["Naturalization"]),
  event("citizenship", "Citizenship", Flag),
  event("travel", "Travel", Route),
  event("military-service", "Military Service", Medal),
  event("military-enlistment", "Military Enlistment", Medal),
  event("military-discharge", "Military Discharge", Medal),
  event("protective-services", "Protective Services", HandHeart),
  protectionEvent("government-protection-status", "Government Protection Status", ShieldCheck),
  protectionEvent("agency-involvement", "Agency Involvement", Landmark, "Life events", HandHeart),
  protectionEvent("social-worker-assignment", "Social Worker Assignment", Users, "Life events", Plus),
  protectionEvent("care-arrangement", "Care Arrangement", HandHeart),
  protectionEvent("care-team-change", "Care Team Change", Users, "Life events", ArrowLeftRight),
  protectionEvent("government-facility-placement", "Government Facility Placement", Building2, "Life events", LogIn),
  protectionEvent("government-facility-release", "Government Facility Release", Building2, "Life events", LogOut),
  protectionEvent("personal-protection-order", "Personal Protection Order", ScrollText, "Life events", ShieldCheck),
  protectionEvent("restraining-order", "Restraining Order", ScrollText, "Life events", Hand),
  protectionEvent("protection-order-change", "Protection Order Change", ScrollText, "Life events", ArrowLeftRight),
  protectionEvent("protection-order-end", "Protection Order End", ScrollText, "Life events", Minus),
  protectionEvent("arrest", "Arrest", Scale),
  protectionEvent("house-arrest", "House Arrest", House, "Life events", Scale),
  protectionEvent("inpatient-care", "Inpatient Care", Cross, "Life events", Building2),
  protectionEvent("daycare-arrangement", "Daycare Arrangement", HandHeart, "Life events", Sun),
  event("criminal-record", "Criminal Record", Scale, "Life events", "A recorded case or document; not a presumption of guilt."),
  event("court-record", "Court Record", Scale),
  event("government-record", "Government Record", Landmark),
  event("census", "Census", Users),
  event("property", "Property", FileCheck2),
  event("land-record", "Land Record", Landmark),
  event("tax-record", "Tax Record", FileText),
  event("medical-event", "Medical Event", HeartPulse, "Life events", "A recorded health-related event; this is not medical advice and does not infer diagnosis."),
  event("hospitalization", "Hospitalization", Cross, "Life events", "A recorded hospital event; details depend on the user's source wording."),
  event("dna-test", "DNA Test", TestTube2),
  event("award", "Award", Award),
  event("religious-event", "Religious Event", Landmark),
  event("community-event", "Community Event", Users),
  event("membership", "Membership", Building2),
  event("will", "Will", ScrollText),
  event("probate", "Probate", Scale),
  event("burial", "Burial", Flower2),
  event("cremation", "Cremation", Flower2),
  event("memorial", "Memorial", Flower2),
  event("death", "Death", Cross),
  event("diagnosis-event", "Diagnosis Event", FileCheck2, "Life events", "A diagnosis event entered from a person's record; the symbol does not diagnose anyone."),
  event("prescription-issued", "Prescription Issued", ScrollText, "Life events", "A recorded prescription document or event; medication instructions remain in the source record."),
  event("treatment-started", "Treatment Started", LogIn),
  event("treatment-ended", "Treatment Ended", LogOut),
  event("therapy-started", "Therapy Started", HandHeart),
  event("therapy-ended", "Therapy Ended", Pause),
  event("hospital-admission", "Hospital Admission", LogIn),
  event("hospital-discharge", "Hospital Discharge", LogOut),
  event("surgery", "Surgery", HeartPulse),
  event("assessment", "Assessment", ListChecks),
  event("accessibility-accommodation-started", "Accessibility Accommodation Started", Accessibility),
  event("accessibility-aid-received", "Accessibility Aid Received", HandHeart),
  event("character-arc", "Character Arc", Route, "Life events", "A recorded development in a fictional character's story."),
  event("canon-event", "Canon Event", FileCheck2, "Life events", "An event marked as part of the character's selected fictional continuity."),
  event("fandom-milestone", "Fandom Milestone", Star, "Life events", "A milestone recorded for a fictional setting or fandom project."),
  { id: "other-event", label: "Other event", group: "Life events", icon: CalendarDays, meaning: "A custom or unrecognized event; its recorded label is retained." },
  disability("disability", "Disability details", PersonStanding, "An explicitly recorded disability description, in the person's preferred terms. No diagnosis is inferred."),
  disability("neurological-impairment", "Neurological impairment", BrainCircuit, "A recorded neurological impairment; the label does not identify a specific cause or condition.", ["neurological disability", "neurologic impairment"]),
  disability("cerebral-palsy", "Cerebral palsy (CP)", BrainCog, "An explicitly recorded cerebral palsy entry. This glyph does not specify movement, communication or cognitive abilities.", ["CP", "C.P."]),
  disability("blindness", "Blindness", EyeOff, "A recorded blindness entry. Preferred terminology and any additional details remain with the person's record.", ["blind"]),
  disability("low-vision", "Low vision", Glasses, "A recorded low-vision entry, distinct from blindness and from a request for large print.", ["partially sighted", "visual impairment"]),
  disability("deafness", "Deafness", EarOff, "A recorded deafness entry. The person's preferred identity, terminology and communication preferences can be recorded separately.", ["deaf"]),
  disability("hard-of-hearing", "Hard of hearing", Ear, "A recorded hard-of-hearing entry, distinct from deafness and from an access request.", ["hearing loss", "hearing impairment"]),
  disability("deafblindness", "Deafblindness", EyeOff, "An explicitly recorded deafblindness entry; no degree of sight or hearing is assumed.", ["deafblind", "deaf-blind", "dual sensory impairment"], EarOff),
  disability("paralysis", "Paralysis", PersonStanding, "A recorded paralysis entry. Affected areas, degree, cause and permanence are not inferred.", ["paralyzed", "paralysed"], Pause),
  disability("limb-loss", "Limb loss or amputation", PersonStanding, "A recorded limb-loss or amputation entry; no cause, affected limb or prosthesis use is assumed.", ["amputee", "amputation", "limb difference"], Minus),
  disability("upper-limb-loss", "Upper-limb loss", Hand, "A recorded upper-limb loss. Side, level and any prosthesis details require explicit entry.", ["arm amputation", "hand amputation", "upper limb amputee"], Minus),
  disability("lower-limb-loss", "Lower-limb loss", Footprints, "A recorded lower-limb loss. Side, level and any prosthesis details require explicit entry.", ["leg amputation", "foot amputation", "lower limb amputee"], Minus),
  disability("speech-impairment", "Speech impairment", MessageCircleOff, "A recorded speech impairment; it does not imply a hearing or cognitive impairment.", ["speech disability"]),
  disability("motor-impairment", "Motor impairment", Move, "A recorded motor impairment; it does not identify an underlying condition or a particular mobility aid.", ["motor disability", "physical impairment"]),
  disability("intellectual-disability", "Intellectual disability", Brain, "An explicitly recorded intellectual disability. No inference is made from another diagnosis or support need.", ["intellectual impairment"]),
  disability("cognitive-impairment", "Cognitive impairment", Brain, "An explicitly recorded cognitive impairment; no cause or severity is inferred.", ["cognitive disability"]),
  disability("dyslexia", "Dyslexia", Type, "An explicitly recorded dyslexia entry. Use the person's preferred wording, and turn on dyslexia-friendly symbols when labels, spacing and text-first cues help.", ["specific learning disorder reading", "reading disability"], Brain),
  disability("dysgraphia", "Dysgraphia", Keyboard, "An explicitly recorded dysgraphia entry. This can mean writing, spelling, motor-writing or written-expression support needs, depending on the person's own record.", ["specific learning disorder written expression", "writing disability"], Brain),
  disability("other-disability", "Other disability", CircleHelp, "A user-described disability outside the current catalogue. Keep the person's preferred wording.", ["custom disability"]),
  need("accessibility", "Accessibility needs", Accessibility, "A general access requirement recorded for this person."),
  need("mobility", "Mobility support", Move, "Recorded support for moving around; not limited to wheelchair use."),
  need("step-free", "Step-free access", Route, "A recorded requirement for a step-free route."),
  need("seating", "Seating support", Armchair, "Recorded seating or positioning requirements."),
  need("hearing", "Hearing support", Ear, "A recorded hearing-related access requirement, not a diagnosis."),
  need("captions", "Captions", Captions, "Captions or a written transcript requested by the person."),
  need("sign-language", "Sign language", Hand, "A recorded sign-language preference. Specify the language in the details."),
  need("vision", "Vision support", Eye, "A recorded vision-related access requirement, not a diagnosis."),
  need("large-print", "Large print", Type, "A recorded preference for larger text."),
  need("low-vision-symbols", "Low-vision symbols", Eye, "Symbols should use larger size, stronger contrast and visible text labels."),
  need("screen-reader", "Screen reader", Speech, "A recorded preference for screen-reader-compatible material."),
  need("dyslexia-friendly-symbols", "Dyslexia-friendly symbols", Type, "Symbols should include plain-language captions, more spacing and less reliance on similar-looking pictograms."),
  need("dysgraphia-friendly-input", "Dysgraphia-friendly input", Keyboard, "Input should support dictation, larger controls, clear labels and slower form workflows."),
  need("color-vision-safe-symbols", "Color-vision safe symbols", Eye, "Symbols and relationship lines should remain understandable without depending on color alone."),
  need("text-first-symbols", "Text-first symbols", FileText, "Show the written label before or instead of the pictogram when that is easier to read."),
  need("communication", "Communication aid", MessageSquareText, "A recorded communication method or aid chosen by the person."),
  need("keyboard-switch", "Keyboard or switch access", Keyboard, "A recorded preference for keyboard or switch input."),
  need("quiet", "Quiet environment", VolumeX, "A recorded preference for a quieter environment."),
  need("low-light", "Reduced lighting", SunDim, "A recorded lighting preference; it does not identify a condition."),
  need("cognitive", "Cognitive support", Brain, "A recorded support preference; it does not label intelligence or diagnose a condition."),
  need("routine", "Predictable routines", ListChecks, "A recorded preference for structure, preparation or a predictable sequence."),
  need("extra-time", "Extra time", Clock3, "Additional time requested for communication, processing or an activity."),
  need("rest", "Rest and energy needs", BatteryMedium, "A recorded preference for pacing or rest breaks."),
  need("personal-assistance", "Personal assistance", HandHeart, "A recorded assistance requirement; not an assumption of dependency."),
  need("health-support", "Health support needs", HeartPulse, "Support needs explicitly recorded by the user; not medical advice or a diagnosis."),
  need("language", "Language or interpreter", Languages, "A language preference or interpreter requirement. This does not imply disability."),
  need("other-support", "Other support", CircleHelp, "A user-described need not represented by another category."),
  { id: "private", label: "Private", group: "Record status", icon: LockKeyhole, meaning: "A privacy flag, not a security or encryption guarantee." },
  { id: "source", label: "Source attached", group: "Record status", icon: FileText, meaning: "A linked source, not proof that an assertion is correct." },
  { id: "review", label: "Needs review", group: "Record status", icon: CircleHelp, meaning: "An explicit research review state." }
];

export const PERSON_GLYPH_GROUPS = ["Disabilities", "Access needs"] as const;
export const DISABILITY_GLYPHS = GLYPHS.filter(glyph => glyph.group === "Disabilities");
export const ACCESS_GLYPHS = GLYPHS.filter(glyph => glyph.group === "Access needs");
export const EVENT_GLYPHS = GLYPHS.filter(glyph => glyph.group === "Life events" || glyph.group === "Relationships").filter(glyph => glyph.eventType);
export const NEED_GLYPHS = [...DISABILITY_GLYPHS, ...ACCESS_GLYPHS];
export const glyphById = (id: string) => GLYPHS.find(glyph => glyph.id === id);
export const eventGlyph = (type: string) => {
  const query = type.trim().toLowerCase();
  return GLYPHS.find(glyph => glyph.eventType?.toLowerCase() === query || glyph.aliases?.some(alias => alias.toLowerCase() === query)) ?? glyphById("other-event")!;
};
export const relationshipGlyph = (role: string, status = "") => {
  const normalizedStatus = status.trim().toLowerCase();
  const statusGlyph = ({ separated: "separation", separation: "separation", divorced: "divorce", divorce: "divorce", annulled: "annulment", annulment: "annulment" } as Record<string, string>)[normalizedStatus];
  if (statusGlyph) return glyphById(statusGlyph)!;
  const normalizedRole = role.trim().toLowerCase();
  const roleGlyph = ({
    parent: "relationship-parent",
    mother: "relationship-parent",
    father: "relationship-parent",
    child: "relationship-child",
    son: "relationship-child",
    daughter: "relationship-child",
    sibling: "relationship-sibling",
    sister: "relationship-sibling",
    brother: "relationship-sibling",
    "immediate family": "relationship-immediate-family",
    immediate: "relationship-immediate-family",
    family: "relationship-immediate-family",
    "extended family": "relationship-extended-family",
    extended: "relationship-extended-family",
    cousin: "relationship-cousin",
    cousins: "relationship-cousin",
    relative: "relationship-extended-family",
    "other relative": "relationship-extended-family",
    "biological relative": "relationship-biological",
    "adoptive relative": "relationship-adopted",
    "foster relative": "relationship-foster",
    "step relative": "relationship-step",
    "in-law": "relationship-in-law",
    inlaw: "relationship-in-law",
    "mother-in-law": "relationship-in-law",
    "father-in-law": "relationship-in-law",
    "sister-in-law": "relationship-in-law",
    "brother-in-law": "relationship-in-law",
    "child-in-law": "relationship-in-law",
    "cousin-in-law": "relationship-cousin-in-law",
    spouse: "relationship-spouse",
    husband: "relationship-spouse",
    wife: "relationship-spouse",
    "former spouse": "relationship-spouse",
    "separated spouse": "separation",
    "annulled spouse": "annulment",
    partner: "relationship-partner",
    "dating partner": "relationship-partner",
    "engaged partner": "engagement",
    fiance: "engagement",
    fiancee: "engagement",
    boyfriend: "relationship-partner",
    girlfriend: "relationship-partner",
    "life partner": "relationship-partner",
    "domestic partner": "relationship-partner",
    "civil union partner": "civil-union",
    "common-law partner": "relationship-partner",
    "polyamorous partner": "relationship-partner",
    "multiple partner relationship": "relationship-partner",
    "ethical non-monogamy": "relationship-partner",
    "open relationship": "relationship-partner",
    "polycule member": "relationship-partner",
    metamour: "relationship-partner",
    "nesting partner": "relationship-partner",
    "anchor partner": "relationship-partner",
    "primary partner": "relationship-partner",
    "secondary partner": "relationship-partner",
    "queerplatonic partner": "relationship-partner",
    "former partner": "relationship-partner",
    "ex-partner": "relationship-partner",
    "co-parent": "relationship-parent",
    guardian: "relationship-guardian",
    ward: "relationship-ward",
    biological: "relationship-biological",
    "biological sibling": "relationship-biological",
    "biological sister": "relationship-biological",
    "biological brother": "relationship-biological",
    "biological parentage": "relationship-biological",
    adoptive: "relationship-adopted",
    adopted: "relationship-adopted",
    "adoptive sibling": "relationship-adopted",
    "adoptive sister": "relationship-adopted",
    "adoptive brother": "relationship-adopted",
    foster: "relationship-foster",
    "foster sibling": "relationship-foster",
    "foster sister": "relationship-foster",
    "foster brother": "relationship-foster",
    "foster parentage": "relationship-foster",
    step: "relationship-step",
    "step sibling": "relationship-step",
    "step sister": "relationship-step",
    "step brother": "relationship-step",
    "half sibling": "relationship-sibling",
    "half sister": "relationship-sibling",
    "half brother": "relationship-sibling",
    "step parentage": "relationship-step",
    "single parent": "single-parent",
    "single mother": "single-mom",
    "single mom": "single-mom",
    "single father": "single-dad",
    "single dad": "single-dad"
  } as Record<string, string>)[normalizedRole];
  return glyphById(roleGlyph || "relationship-partner")!;
};
export const glyphMatchesQuery = (glyph: GlyphDefinition, query: string) => [glyph.label, glyph.group, glyph.meaning, ...(glyph.aliases ?? [])].join(" ").toLowerCase().includes(query.trim().toLowerCase());

export function groupPersonNeeds(needs: PersonNeed[]) {
  return [...PERSON_GLYPH_GROUPS, "Other annotations"].map(group => ({
    group,
    needs: needs.filter(need => {
      const definition = NEED_GLYPHS.find(glyph => glyph.id === need.glyphId);
      return (definition?.group ?? "Other annotations") === group;
    })
  })).filter(group => group.needs.length > 0);
}

export function createPersonNeed(glyphId: string, detail: string, sourceId?: string, recordLabel?: string): PersonNeed {
  const glyph = NEED_GLYPHS.find(entry => entry.id === glyphId);
  if (!glyph) throw new Error("Choose a disability or access-needs symbol.");
  return { id: makeId("need"), glyphId, label: recordLabel?.trim() || glyph.label, detail: detail.trim(), sourceId, private: true };
}
