export type GlossarySource = {
  id: string;
  title: string;
  url: string;
};

export type GlossaryEntry = {
  term: string;
  meaning: string;
  category: string;
  aliases: readonly string[];
  sourceIds: readonly string[];
};

import {
  BELIEF_OPTIONS,
  ACCESSIBILITY_AID_OPTIONS,
  DEGENERATIVE_CONDITION_OPTIONS,
  DISABILITY_CONDITION_OPTIONS,
  IDENTITY_OPTIONS,
  MEDICAL_RECORD_TYPE_OPTIONS,
  MENTAL_HEALTH_OPTIONS,
  MENTAL_HEALTH_SUPPORT_OPTIONS,
  PHYSICAL_CONDITION_OPTIONS,
  RELIGION_OPTIONS,
  RELIGIOUS_PRACTICE_OPTIONS,
  type PersonFactCatalogEntry
} from "./personFactCatalog";

export const GLOSSARY_NOTE = "These are plain-language record explanations, not medical, mental-health, religious, or legal advice. Legal meanings and rules vary by jurisdiction (place) and by date. A label alone does not establish guilt, legal status, parentage, a diagnosis, or a case outcome. Medical and mental-health terms can change by time and place; KinForge does not diagnose anyone. Check the original record, the person's preferred wording, and local law.";

export const GLOSSARY_SOURCES: readonly GlossarySource[] = [
  { id: "civil-union", title: "New Jersey Department of Health: civil unions", url: "https://www.nj.gov/health/vital/registration-vital/civil-union-licenses/" },
  { id: "custody", title: "California Courts: child custody and parenting time", url: "https://selfhelp.courts.ca.gov/what-to-know-about-child-custody-parenting-time" },
  { id: "annulment", title: "California Courts: annulment", url: "https://selfhelp.courts.ca.gov/divorce-california/annulment/legal-reasons" },
  { id: "separation", title: "California Courts: legal separation", url: "https://selfhelp.courts.ca.gov/divorce-california/legal-separation" },
  { id: "protection-order", title: "Singapore Courts: personal protection orders", url: "https://www.judiciary.gov.sg/family/apply-personal-protection-order" },
  { id: "restraining-order", title: "California Courts: domestic violence restraining orders", url: "https://selfhelp.courts.ca.gov/DV-restraining-order" },
  { id: "child-protection", title: "Singapore MSF: child protection system", url: "https://www.msf.gov.sg/what-we-do/break-the-silence/protection-system/child-protection-system" },
  { id: "fostering", title: "Singapore MSF: fostering", url: "https://www.msf.gov.sg/what-we-do/fostering" },
  { id: "kinship-care", title: "North Carolina DHHS: kinship and relative care", url: "https://www.ncdhhs.gov/divisions/social-services/child-welfare-services/foster-family-recruitment/kinshiprelative-care" },
  { id: "reunification", title: "US Children's Bureau: reunification (PDF)", url: "https://www.childwelfare.gov/pubPDFs/reunification.pdf" },
  { id: "lds-ordinances", title: "Church of Jesus Christ of Latter-day Saints: ordinance meanings", url: "https://www.churchofjesuschrist.org/tools/help/ordinance-preparation-system-help-documentation?lang=eng" },
  { id: "lds-proxy", title: "Church handbook: ordinances for the deceased", url: "https://www.churchofjesuschrist.org/study/manual/general-handbook/28?lang=eng" },
  { id: "latter-day-saints", title: "The Church of Jesus Christ of Latter-day Saints: About Us", url: "https://www.churchofjesuschrist.org/learn/about-us?lang=eng" },
  { id: "mental-health-topics", title: "National Institute of Mental Health: Health Topics", url: "https://www.nimh.nih.gov/health/topics" },
  { id: "autism-spectrum", title: "CDC: About Autism Spectrum Disorder", url: "https://www.cdc.gov/autism/about/index.html" },
  { id: "who-disability-health", title: "World Health Organization: Disability and health", url: "https://www.who.int/news-room/fact-sheets/detail/disability-and-health" },
  { id: "cdc-disability-health", title: "CDC: Disability and Health Overview", url: "https://www.cdc.gov/disability-and-health/about/index.html" },
  { id: "ada-disability-definition", title: "ADA.gov: Guide to Disability Rights Laws", url: "https://www.ada.gov/resources/disability-rights-guide/" },
  { id: "medlineplus-degenerative", title: "MedlinePlus: Neurodegenerative Diseases", url: "https://medlineplus.gov/degenerativenervediseases.html" },
  { id: "ninds-disorders", title: "NIH NINDS: Disorders", url: "https://www.ninds.nih.gov/health-information/disorders" },
  { id: "nia-alzheimers", title: "NIH National Institute on Aging: Alzheimer's Disease and Related Dementias", url: "https://www.nia.nih.gov/health/alzheimers-and-dementia" },
  { id: "lgbtqia-wiki", title: "LGBTQIA+ Wiki: LGBTQIA+ Wiki", url: "https://lgbtqia.fandom.com/wiki/LGBTQIA%2B_Wiki" },
  { id: "hrc-glossary", title: "Human Rights Campaign: Glossary of Terms", url: "https://www.hrc.org/resources/glossary-of-terms" },
  { id: "lgbt-resource-glossary", title: "UCSF LGBT Resource Center: Glossary", url: "https://lgbt.ucsf.edu/glossary-terms" },
  { id: "religious-diversity", title: "Pew Research Center: Religious Diversity Around the World", url: "https://www.pewresearch.org/religion/2026/02/12/religious-diversity-around-the-world/" }
];

type Definition = readonly [term: string, meaning: string, aliases?: readonly string[], sourceIds?: readonly string[]];

function category(name: string, definitions: readonly Definition[]): GlossaryEntry[] {
  return definitions.map(([term, meaning, aliases = [], sourceIds = []]) => ({ term, meaning, category: name, aliases, sourceIds }));
}

function catalogCategory(name: string, entries: readonly PersonFactCatalogEntry[]): GlossaryEntry[] {
  return entries.map(entry => ({ term: entry.label, meaning: entry.meaning, category: name, aliases: entry.aliases || [], sourceIds: entry.sourceIds || [] }));
}

export const GLOSSARY_ENTRIES: readonly GlossaryEntry[] = [
  ...category("Life events", [
    ["Birth", "When a person was born."],
    ["Naming", "An occasion when a person was given or formally announced a name."],
    ["Baptism", "A Christian ceremony using water to welcome someone into the faith. It can happen at any age."],
    ["Christening", "A Christian ceremony, often for a baby, that usually includes baptism and naming."],
    ["Blessing", "A religious or spiritual ceremony asking for care, guidance, or well-being."],
    ["Residence", "A place where someone lived during a particular period."],
    ["Address Change", "When someone changed their recorded home or mailing address."],
    ["Education", "Schooling, study, or training a person took part in."],
    ["Graduation", "When a person completed a course or stage of education."],
    ["Occupation", "The kind of work someone does or did, such as teaching or farming."],
    ["Employment Start", "When a person began a job."],
    ["Employment End", "When a person stopped a particular job. The reason may be recorded separately."],
    ["Retirement", "When someone stopped their main working career, fully or partly."],
    ["Immigration", "Moving into a country to live there."],
    ["Emigration", "Leaving a country to live in another one."],
    ["Naturalisation", "The legal process of becoming a citizen of a country after birth. Requirements vary by country and time.", ["Naturalization"]],
    ["Citizenship", "A person's legal membership of a country, with rights and duties under its laws."],
    ["Travel", "A journey or visit away from the place someone usually lives."],
    ["Military Service", "Time spent serving in a country's armed forces."],
    ["Military Enlistment", "When a person formally joined the armed forces."],
    ["Military Discharge", "When a person was formally released from military service. The discharge type and reason need their own record."],
    ["Engagement", "An agreement or announced intention to marry."],
    ["Engagement Ended", "When a recorded engagement ended before marriage. It does not by itself say who ended it or why."],
    ["Betrothal", "A formal or traditional promise or arrangement to marry, with meanings that vary by culture, religion, place, and date."],
    ["Relationship Started", "When a romantic, partner, queerplatonic, dating, or other relationship began, using the people involved or source wording."],
    ["Dating Started", "When people began dating or seeing each other as recorded by the source or their own wording."],
    ["Courtship Started", "When a courtship began. Courtship customs vary by family, culture, religion, and time period."],
    ["Relationship Milestone", "A notable point in a relationship, such as becoming exclusive, changing commitments, meeting family, moving closer, or another recorded milestone."],
    ["Breakup", "When a dating, partner, romantic, queerplatonic, or other relationship ended. It does not automatically mean marriage, civil union, or legal status changed."],
    ["Partner Breakup", "A breakup between partners. Use notes to record the relationship type and whether contact, co-parenting, or friendship continued."],
    ["Reconciliation", "When people resumed a relationship, contact, co-parenting, or household arrangement after conflict, separation, or breakup."],
    ["Cohabitation Started", "When people began living together in the same home. Living together does not by itself prove marriage, romance, or legal partnership."],
    ["Cohabitation Ended", "When people stopped living together. It does not by itself prove a breakup, divorce, or legal separation."],
    ["Commitment Ceremony", "A ceremony or event where people publicly or privately marked a committed relationship. Legal recognition depends on place and date."],
    ["Civil Partnership", "A registered partnership recognised by law in some jurisdictions. Rights and requirements vary by country and date."],
    ["Domestic Partnership", "A relationship status recognised by some employers, governments, or institutions. Legal effects vary by place and policy."],
    ["Polycule Joined", "When a person became part of a polycule or named consensual non-monogamous relationship network."],
    ["Polycule Left", "When a person left a polycule or named consensual non-monogamous relationship network."],
    ["Metamour Link", "A recorded connection to a partner's partner, especially in polyamorous or consensual non-monogamous contexts."],
    ["Queerplatonic Partnership", "A committed relationship that does not fit neatly into friendship or romance categories, using the people's own wording."],
    ["Relationship Agreement", "A recorded agreement about a relationship, such as exclusivity, boundaries, caregiving, co-parenting, openness, or household responsibilities."],
    ["Relationship Status Change", "A change in how a relationship is described, such as dating to engaged, partnered to separated, private to public, or another source-backed status."],
    ["Marriage", "A union recorded as a marriage. Its legal recognition depends on the place, date, and applicable rules.", ["Married"]],
    ["Marriage Banns", "A public announcement of an intended marriage, traditionally made before the wedding so objections can be raised."],
    ["Marriage License", "Official permission to marry where a licence is required. It does not by itself prove that the wedding took place.", ["Marriage Licence"]],
    ["Separation", "When a couple stops living together as a couple or records a separation. Separation alone does not end a marriage.", ["Separated"], ["separation"]],
    ["Trial Separation", "A temporary separation intended as a trial or review period. It does not automatically end a marriage or partnership."],
    ["Legal separation", "A formal legal arrangement for living apart while still married. Its effects depend on local law.", [], ["separation"]],
    ["Divorce Filing", "When someone submits a request to legally end a marriage. Filing is not a completed divorce.", [], ["separation"]],
    ["Divorce Decree", "The court order or final legal document completing or recording a divorce, depending on local law."],
    ["Divorce", "The legal ending of a marriage. The effective date comes from the final legal record.", ["Divorced"], ["separation"]],
    ["Annulment", "A legal decision that a marriage was not legally valid. A religious annulment is a separate matter and may not change civil status.", ["Annulled"], ["annulment"]],
    ["Annulment Filing", "When someone submits a request for annulment. Filing is not the same as a completed annulment decision.", [], ["annulment"]],
    ["Partnership", "A relationship between people recorded as partners. This label alone does not say whether they are married or legally registered."],
    ["Civil Union", "A legally recognised couple relationship registered under a civil-union law. Its rights may resemble marriage, but recognition and rules vary by place and date.", [], ["civil-union"]],
    ["Census", "An official count of people, often recording household members, ages, jobs, and addresses on a particular date."],
    ["Property", "Land, buildings, or other things a person owned or had an interest in."],
    ["Land Record", "A document about land ownership, boundaries, sale, or use."],
    ["Tax Record", "A record of taxes assessed or paid, sometimes listing property, income, or household details."],
    ["Medical Event", "A dated occurrence involving someone's health or care, such as treatment or an operation."],
    ["Diagnosis Event", "When a diagnosis, assessment result, or clinician finding was recorded. KinForge stores the source and does not diagnose anyone."],
    ["Prescription Issued", "When a prescription was issued or recorded. It does not mean the medication was taken exactly as prescribed."],
    ["Treatment Started", "When a treatment, therapy, medication, support plan, or care programme began."],
    ["Treatment Ended", "When a treatment, therapy, medication, support plan, or care programme ended or was recorded as stopped."],
    ["Therapy Started", "When therapy or rehabilitation began, such as counselling, OT, physiotherapy, speech therapy, or another service."],
    ["Therapy Ended", "When therapy or rehabilitation ended, paused, or transferred to another service."],
    ["Hospital Admission", "When a person was admitted to a hospital or inpatient facility for care."],
    ["Hospital Discharge", "When a person was discharged from a hospital or inpatient facility."],
    ["Surgery", "An operation or surgical procedure. Record date, hospital, clinician, reason, outcome, and source if known."],
    ["Assessment", "A formal or informal assessment, such as medical, psychological, educational, occupational therapy, speech, or functional assessment."],
    ["Accessibility Accommodation Started", "When an access accommodation began, such as captions, ramp access, flexible scheduling, assistive software, or adjusted duties."],
    ["Accessibility Aid Received", "When a mobility, communication, sensory, medical, or access aid was received, prescribed, fitted, repaired, or issued."],
    ["Hospitalization", "A stay after being admitted to a hospital for care.", ["Hospitalisation"]],
    ["Work Contract Signed", "When a work, employment, freelance, agency, or character-job contract was signed or recorded."],
    ["Employment Contract", "A contract or agreement setting work role, pay, duties, hours, confidentiality, or other employment terms."],
    ["Company Joined", "When a person or character began working for, serving in, or joining a company, organisation, guild, agency, or workplace."],
    ["Company Left", "When a person or character stopped working for, serving in, or being attached to a company, organisation, guild, agency, or workplace."],
    ["Promotion", "When a person received a higher role, rank, grade, title, pay band, or status at work or in an organisation."],
    ["Workplace Accommodation", "A work or school adjustment made for disability, health, access, religious, caregiving, or other needs."],
    ["Work Transfer", "When a person moved to a different role, department, branch, posting, workplace, or company unit."],
    ["Freelance Contract", "A contract for independent, freelance, commission, or project-based work."],
    ["Character Arc", "A fictional-development event marking an important change in a character's personality, role, relationship, goal, or story direction."],
    ["Canon Event", "A story event treated as canon in the selected continuity. Canon status should be recorded with notes because versions may differ."],
    ["Fandom Milestone", "A fictional or fandom record milestone, such as first appearance, design change, title reveal, lore update, or fanwork release."],
    ["DNA Test", "A test of genetic material. For family history it can help compare ancestry or possible relatives; results need careful interpretation."],
    ["Award", "A prize, honour, or other recognition a person received."],
    ["Religious Event", "An occasion connected with someone's faith or religious community."],
    ["Community Event", "An occasion involving a local group or community."],
    ["Membership", "Belonging to an organisation, club, or other group."],
    ["Will", "A document stating a person's wishes for their property after death. Legal validity depends on the applicable law."],
    ["Probate", "The legal process for dealing with a deceased person's estate, including checking a will when there is one."],
    ["Death", "When a person's life ended.", ["Deceased"]]
  ]),
  ...category("Care, custody, and government", [
    ["Adoption", "A legal process that creates a parent-child relationship. The details and effects depend on the adoption law and order.", ["Adopted"]],
    ["Guardianship", "Legal authority to care for someone or make specified decisions for them. The authority can be limited; it is different from adoption."],
    ["Foster Care", "Care for a child who is living away from their parents, usually with approved carers for a period of time. Foster care is different from adoption.", ["Foster"], ["fostering"]],
    ["Child Custody", "Who has responsibility for a child's care, living arrangements, or important decisions. Legal custody and day-to-day care can be different.", ["Custody"], ["custody"]],
    ["Legal custody", "The authority to make important decisions for a child, such as schooling and health care.", [], ["custody"]],
    ["Physical custody", "The arrangement for where a child lives and who provides their day-to-day care.", [], ["custody"]],
    ["Custody removal", "A recorded decision taking some or all custody away from a parent or carer. It does not by itself mean adoption, permanent loss of parental rights, or criminal guilt.", ["Custody removed from parents", "Custody removed", "Removal record"], ["custody", "child-protection"]],
    ["Custody change", "A change in who has custody, where a child lives, or who can make decisions for them. The record should say what changed.", ["Custody change record"], ["custody"]],
    ["Custody restoration", "Returning some or all custody to someone who previously held it. The decision states which responsibilities or rights return.", ["Custody restored"], ["custody"]],
    ["Protective Services", "Services that assess safety concerns and arrange support or protection for children or vulnerable adults. Involvement alone does not prove abuse or criminal guilt.", ["Child protective services", "Child in protective services", "Protective Services Record"], ["child-protection"]],
    ["Protective services involvement", "When a protection service becomes involved in assessment, support, or a care plan. This alone does not establish that an allegation was proved.", [], ["child-protection"]],
    ["Government protection started", "When a recorded period of protection or supervision by a public authority began. The record should identify the arrangement and authority.", ["Government protection start"], ["child-protection"]],
    ["Government protection ended", "When a recorded protection or supervision arrangement ended. This does not by itself say where the person went or whether another arrangement began.", ["Government protection end"], ["child-protection"]],
    ["Government protection review", "A meeting or assessment to check a protection plan and decide whether it should continue or change. A review alone does not mean the plan ended.", [], ["child-protection"]],
    ["Protection order", "A court order intended to protect someone from specified harm, such as violence or harassment. The actual restrictions, duration, and legal effect are in the order.", ["Protective order"], ["protection-order", "restraining-order"]],
    ["Personal protection order", "A protection order for a person. In Singapore family proceedings, a PPO concerns protection from family violence; the meaning elsewhere can differ.", ["PPO", "Personal Protection Order Record"], ["protection-order"]],
    ["Restraining order", "A court order telling someone to stop specified actions, often contact, harassment, or approaching a person. The order itself states what is restricted; it is not by itself a criminal conviction.", ["Restraining Order Record"], ["restraining-order"]],
    ["Emergency placement", "An urgent, usually temporary arrangement for someone to stay with a carer or at a care facility while immediate needs are addressed.", [], ["kinship-care"]],
    ["Foster placement", "When a child starts living with a particular foster carer or foster family. It records that placement, not an adoption.", [], ["fostering"]],
    ["Foster placement ended", "When a particular foster placement stopped. The child may move to another placement, return home, or enter another arrangement; the label does not say which.", ["Foster ended", "Foster placement end"], ["fostering", "reunification"]],
    ["Social worker", "A professional who helps people and families with support, care, and practical difficulties. Their role depends on the service involved.", ["Social worker name"]],
    ["Social worker assigned", "When a named social worker was given responsibility for helping with or managing a person's case. Assignment alone does not say why help was needed.", ["Social Worker Assignment"]],
    ["Government facility", "A place run by or linked to a public authority, such as a care home or hospital. This label alone does not mean a prison or detention centre.", ["Government Facility Record"]],
    ["Government facility admission", "When a person began a stay at a government facility. Admission alone does not establish detention, criminal guilt, or a diagnosis.", ["Government Facility Placement"]],
    ["Government facility discharge", "When a person's stay at a government facility ended. The reason and next living arrangement need to be recorded separately.", ["Government Facility Release"]],
    ["Kinship care", "Care of a child by relatives or trusted people already close to the family. It can be an informal family arrangement or involve an agency or court.", [], ["kinship-care"]],
    ["Reunification", "A child returning to live with their parent or family after time in care elsewhere. Support or supervision may continue; returning home does not automatically close a case.", ["Family reunification"], ["reunification"]],
    ["Criminal Record", "An official record of criminal justice matters, which may include arrests, charges, or convictions. An entry is not automatically proof of guilt."],
    ["Criminal Case", "A legal proceeding about an alleged offence. Being named in a case does not mean a person was convicted."],
    ["Arrest", "When an authority takes a person into custody under legal powers. Arrest alone does not establish guilt.", ["Arrest Record"]],
    ["House arrest", "A legal restriction requiring a person to stay at a specified home, with any exceptions set by the order. It does not by itself identify a conviction.", ["House Arrest Record"]],
    ["Conviction", "A court's formal finding that someone is guilty of an offence. It is different from an accusation, charge, or arrest."],
    ["Court Record", "A document from court proceedings, such as an application, hearing note, or decision. Check which kind of document it is."],
    ["Government Record", "A document created or kept by a public authority, such as a certificate, registration, or case file.", ["Government events"]],
    ["Government Identifier", "An identifying number or code issued by a public authority, such as a national identification number. It may be sensitive."],
    ["Agency", "The organisation responsible for a service or case, such as a social services department.", ["Social worker agency"]],
    ["Agency involvement", "When an organisation becomes involved in providing support, assessment, or oversight. The record should say which agency and what role it had."],
    ["Care arrangement", "Who is providing a person's care, where that care happens, and any recorded conditions. A care arrangement alone does not establish legal custody."],
    ["Care team change", "A change to the people or services involved in someone's care, such as a new doctor, social worker, or care provider."],
    ["Protection order change", "A recorded change to a protection order's conditions, scope, or duration. The updated order states what changed.", [], ["protection-order", "restraining-order"]],
    ["Protection order end", "When a particular protection order expired or was ended by the relevant authority. This alone does not establish that all other orders ended.", ["Protection order ended"], ["protection-order", "restraining-order"]],
    ["Inpatient care", "Care provided during an admitted stay at a hospital or other treatment facility.", ["In-patient Record"]],
    ["Daycare arrangement", "A recorded arrangement for care during the day, such as a childcare centre or adult day service.", ["Daycare Record"]],
    ["Social Worker Record", "A document or note about a social worker's involvement, assessments, or support."],
    ["Doctor or Care Record", "A document or note about medical treatment, a care plan, or the professionals providing care."],
    ["Other Government File", "A government-related document outside the listed file types. Its title and contents explain what it records."],
    ["Case number", "The reference number used by an agency or court to identify a particular case."],
    ["Adopted Status", "What the records say about a person's adoption, including whether it was completed or is uncertain."],
    ["Foster Status", "Whether and when someone was in foster care, as stated in the record.", ["Foster record"], ["fostering"]],
    ["Protective Status", "The recorded protection or supervision arrangement, if any. The label alone does not say that an allegation was proved.", ["Government protection status", "Government Protection Record"], ["child-protection"]],
    ["Custody Status", "The custody arrangement stated in the record, including who holds responsibility and when it applies.", ["Custody notes"], ["custody"]],
    ["Jurisdiction", "The place or legal authority whose rules apply to a case, such as a country, state, or court area."]
  ]),
  ...category("Personal facts", [
    ["Age", "How old a person was at the date of a record, usually in years."],
    ["Age at Event", "How old a person was when a particular event happened."],
    ["Age Range", "A lower and upper estimate of someone's age, such as 30 to 35 years."],
    ["Eye Color", "The recorded colour of a person's eyes.", ["Eye Colour"]],
    ["Hair Color", "The recorded colour of a person's hair at a particular time.", ["Hair Colour"]],
    ["Hair Texture", "How someone's hair was described, such as straight, wavy, or curly."],
    ["Height", "How tall a person was. The value needs a unit, such as centimetres or feet."],
    ["Weight", "How heavy a person was at the recorded time. The value needs a unit, such as kilograms or pounds."],
    ["Body Type", "A source's description of someone's general body shape. It is not a health assessment."],
    ["Build", "A source's description of someone's frame or physique, such as slight or broad."],
    ["Complexion", "How a source described the appearance of someone's skin. Historical descriptions may use outdated language."],
    ["Skin Tone", "The recorded shade of a person's skin. It does not determine ethnicity or nationality."],
    ["Dominant Hand", "The hand a person usually favours for tasks such as writing, or a record that they use both hands."],
    ["Distinguishing Marks", "Visible features used to describe or identify someone, such as a scar or birthmark."],
    ["Birthmark", "A mark on the skin present from birth or appearing soon afterwards."],
    ["Scar", "A lasting mark on the skin after an injury or operation."],
    ["Tattoo", "A design or wording made by putting pigment into the skin."],
    ["Physical Description", "A written account of how a person looked at a particular time."],
    ["Blood Type", "A person's blood group, such as A positive or O negative. It is not enough to prove a family relationship."],
    ["Allergy", "A recorded immune reaction to a substance, such as a food or medicine."],
    ["Medication", "A medicine a person was recorded as taking. This is a history entry, not a treatment recommendation."],
    ["Medical Condition", "A health condition described in a record. Its details and dates matter."],
    ["Diagnosis", "A health professional's identification of a condition, as documented in the source. KinForge stores the record; it does not diagnose anyone."],
    ["Diagnosis criteria", "The recorded criteria, standard, assessment findings, test results, or clinical explanation used to support a diagnosis. Preserve the clinician or source wording."],
    ["Physical condition", "A physical or medical condition recorded from a person, clinician, or source. The exact diagnosis date, provider, criteria, and files should be kept with the record."],
    ["Chronic condition", "A condition that lasts a long time or requires ongoing management. Its severity and access needs can change over time."],
    ["Degenerative condition", "A condition that tends to progress or worsen over time, such as some neurological, muscle, joint, or eye conditions. Record the specific condition and source."],
    ["Pain condition", "A condition involving persistent, recurring, or disabling pain. Record location, triggers, source diagnosis, treatment, and functional impact."],
    ["Trauma-related condition", "A physical, mental-health, or nervous-system condition connected with trauma or injury. Record source wording and do not infer cause without documentation."],
    ["Neurological condition", "A condition involving the brain, spinal cord, nerves, or neuromuscular system."],
    ["Developmental condition", "A condition beginning during development that may affect physical, learning, language, behaviour, sensory, or social areas."],
    ["Physical disability", "A disability affecting body movement, stamina, strength, pain, balance, dexterity, or physical access."],
    ["Sensory disability", "A disability affecting vision, hearing, smell, touch, sensory processing, or environmental tolerance."],
    ["Communication disability", "A disability affecting speech, language, voice, fluency, understanding, writing, or communication access."],
    ["Functional limitation", "A recorded difficulty with an activity such as moving, seeing, hearing, learning, self-care, communication, working, or participating in daily life."],
    ["Health support need", "A practical or health-related support need such as medication timing, emergency plan, rest breaks, equipment, personal care, or monitoring."],
    ["Access accommodation", "A change or support that reduces a barrier, such as captions, large print, ramps, flexible scheduling, plain language, or fragrance-free space."],
    ["Disability or Access Need", "A disability or a support need that affects access or daily life, recorded in the person's preferred terms."],
    ["Mobility Aid", "Equipment that helps someone move around, such as a wheelchair, cane, or walker."],
    ["Assistive Technology", "Equipment or software that supports access or everyday tasks, such as a screen reader or communication device."],
    ["DNA Kit", "The test kit or reference number linking a person to results from a DNA testing provider."],
    ["Ethnicity Estimate", "A DNA provider's estimate of ancestry based on comparison groups. It can change and does not define a person's cultural identity."],
    ["Genetic Group", "A group a DNA provider associates with shared ancestry or family history. It is an estimate, not proof of a specific relationship."],
    ["Haplogroup", "A branch of a genetic family tree identified by shared DNA changes, usually along one maternal or paternal line. It is only one part of someone's ancestry."],
    ["Religion", "A person's recorded faith, belief tradition, or religious affiliation."],
    ["Belief", "A person's recorded belief, worldview, or spiritual position. A label should come from the person's own wording or a reliable source."],
    ["Religious practice", "A recorded religious or cultural practice. The meaning and rules can differ between communities and individuals, so keep the person's wording and source."],
    ["Mental health condition", "A mental-health or neurodevelopmental condition recorded from a source or the person's own description. KinForge does not diagnose anyone."],
    ["Mental health support need", "A recorded mental-health support or accommodation need. It does not disclose a diagnosis unless the person or source says so."],
    ["Language", "A language someone speaks, understands, writes, or used in a record."],
    ["Nationality", "A person's recorded connection to a nation. Some records mean legal nationality; others mean national identity, so the source matters."],
    ["Ethnicity", "A person's cultural or ancestral group identity. It is different from citizenship and a DNA estimate."],
    ["Clan or Tribe", "A named family, community, or people with which someone identifies or is recorded as belonging. Membership rules are set by that community."],
    ["Education Level", "The stage of education a person reached, such as primary school or university."],
    ["School", "An educational institution a person attended."],
    ["Degree", "An academic qualification awarded after completing a course, such as a bachelor's degree."],
    ["Employer", "The person or organisation someone worked for."],
    ["Job Title", "The name of a person's role at work, such as head teacher or clerk."],
    ["Cause of Death", "The reason for a person's death as stated in a medical or other source. This field does not establish a cause on its own."],
    ["Medical Note", "Additional recorded information about someone's health or care."],
    ["Condition Type", "The broad kind of condition recorded, such as mental-health, neurological, physical, developmental, genetic, chronic, degenerative, or accessibility-related."],
    ["Disorder Type", "A more specific disorder branch or subtype. Use the clinician/source wording or the person's own wording."],
    ["Body System", "The body system or area affected, such as nervous system, vision, hearing, heart, lungs, skin, mobility, pain, or multiple systems."],
    ["Onset Date", "When symptoms, traits, injury, or condition signs began, if recorded. This can differ from the diagnosis date."],
    ["Review Date", "When a diagnosis, care plan, accommodation, treatment, or support record should be reviewed or was reviewed."],
    ["Care Level", "The level or setting of care, such as self-managed, primary care, specialist care, therapy, outpatient, inpatient, or residential support."],
    ["Military Rank", "A person's level or position in the armed forces, such as private or captain."],
    ["Title", "A name placed before or after someone's name to show a role, honour, or rank, such as Dr or Sir."],
    ["Nickname", "An informal name used for someone."],
    ["Preferred Name", "The name a person chooses to be called. It may differ from the name on official documents."],
    ["Name Pronunciation", "A guide to how a person's name is spoken."],
    ["Given name", "A personal name, often called a first name. Name order varies between cultures.", ["First name"]],
    ["Family name", "A name shared with family members, often called a surname. Not everyone uses one.", ["Surname", "Last name"]],
    ["Alias", "Another name under which a person is known or appears in a record.", ["Aliases"]],
    ["In-patient status", "Whether someone is recorded as staying in a hospital or care setting after admission.", ["Inpatient status", "Inpatient"]],
    ["Daycare status", "Whether someone is recorded as attending a service that provides care during the day."],
    ["Doctor", "A medical professional recorded as providing or overseeing care.", ["Doctor name"]],
    ["Doctor practice / hospital", "The clinic, practice, or hospital linked to the recorded doctor."],
    ["Care team notes", "Notes about the people and services involved in someone's care."],
    ["Birth method", "How the birth took place, as recorded in the source."],
    ["Natural birth", "A term often used for vaginal birth, sometimes specifically without certain medical interventions. Keep the source's intended meaning."],
    ["C-section", "An operation in which a baby is delivered through openings made in the abdomen and uterus.", ["Caesarean section", "Cesarean section"]],
    ["Surrogacy", "An arrangement in which someone carries a pregnancy for an intended parent or parents. Legal parenthood depends on the applicable law."],
    ["Assisted reproduction", "Medical help to achieve pregnancy, such as insemination or IVF."],
    ["Birth assistant / surrogate / notes", "The person who helped at the birth, any recorded surrogacy details, or related notes. These are different roles and do not by themselves establish parentage."],
    ["Birth notes", "Additional information from the record about a person's birth."]
  ]),
  ...category("Religious records", [
    ["LDS", "An abbreviation for Latter-day Saints, used in family-history records for The Church of Jesus Christ of Latter-day Saints."],
    ["LDS: Baptism", "A Latter-day Saint ceremony of immersion in water. A family-history record may describe a ceremony performed in life or by a living person on behalf of someone deceased.", [], ["lds-ordinances", "lds-proxy"]],
    ["LDS: Confirmation", "A Latter-day Saint ceremony confirming church membership and conferring the gift of the Holy Ghost. A record may describe a ceremony performed on behalf of someone deceased.", [], ["lds-ordinances", "lds-proxy"]],
    ["LDS: Initiatory", "Preparatory Latter-day Saint temple ceremonies before the endowment, involving symbolic washing, anointing, and blessings.", [], ["lds-ordinances"]],
    ["LDS: Endowment", "A Latter-day Saint temple ceremony involving religious instruction, promises to God, and blessings.", [], ["lds-ordinances"]],
    ["LDS: Sealing to Parents", "A temple ceremony joining children and parents eternally according to Latter-day Saint belief. It does not itself establish biological parentage.", [], ["lds-ordinances", "lds-proxy"]],
    ["LDS: Sealing to Spouse", "A temple ceremony joining spouses eternally according to Latter-day Saint belief. Civil marriage recognition depends on the legal authority involved.", [], ["lds-ordinances", "lds-proxy"]]
  ]),
  ...catalogCategory("Religions", RELIGION_OPTIONS),
  ...catalogCategory("Beliefs and worldviews", BELIEF_OPTIONS),
  ...catalogCategory("Religious practices", RELIGIOUS_PRACTICE_OPTIONS),
  ...catalogCategory("Identity, sexuality, gender and LGBTQIA2+", IDENTITY_OPTIONS),
  ...catalogCategory("Mental health and neurodevelopment", MENTAL_HEALTH_OPTIONS),
  ...catalogCategory("Mental health support", MENTAL_HEALTH_SUPPORT_OPTIONS),
  ...catalogCategory("Physical and chronic conditions", PHYSICAL_CONDITION_OPTIONS),
  ...catalogCategory("Degenerative conditions", DEGENERATIVE_CONDITION_OPTIONS),
  ...catalogCategory("Disabilities and access needs", DISABILITY_CONDITION_OPTIONS),
  ...catalogCategory("Mobility and accessibility aids", ACCESSIBILITY_AID_OPTIONS),
  ...catalogCategory("Medical files and diagnosis records", MEDICAL_RECORD_TYPE_OPTIONS),
  ...category("Medical, work, and company file types", [
    ["Diagnosis File", "A document or attachment supporting or recording a diagnosis, assessment finding, clinician letter, or diagnostic explanation."],
    ["Prescription File", "A prescription or medication-related file. It records history and must not be treated as medical advice."],
    ["Treatment File", "A file about treatment, therapy, procedure, rehabilitation, medication, support plan, or care programme."],
    ["Treatment Plan", "A plan for treatment or care, including goals, steps, review dates, clinician responsibilities, and safety information."],
    ["Referral Letter", "A letter sending a person to another clinician, specialist, hospital, therapist, or service."],
    ["Doctor's Letter", "A letter from a doctor or medical professional about diagnosis, treatment, fitness, accommodations, or care."],
    ["Specialist Report", "A report from a specialist clinician or service."],
    ["Work Contract", "A contract or agreement for work, employment, freelance, character job, agency, guild, or company role."],
    ["Company File", "A company or organisation file connected to a person or fictional character, such as HR, role, project, badge, or employment material."],
    ["Employee File", "A workplace record about an employee, worker, contractor, or character's job history."],
    ["Job Offer", "A recorded offer of work or a role, whether accepted, declined, pending, or fictional."],
    ["Job Description", "A description of a role's duties, responsibilities, reporting line, and expectations."],
    ["Role Assignment", "A record that someone was assigned a role, post, department, mission, company team, or fictional work position."],
    ["Workplace Accommodation File", "A file about workplace changes or supports for disability, health, access, religion, caregiving, or other needs."],
    ["Leave or Absence File", "A workplace file about leave, absence, medical leave, parental leave, sabbatical, or time away."],
    ["Performance Review", "A workplace review or evaluation of performance, goals, progress, conduct, or development."],
    ["Promotion Record", "A record of promotion, rank change, title change, pay band change, or increased responsibility."],
    ["Pay or Payroll File", "A file about pay, payroll, wages, salary, invoices, stipends, or compensation."],
    ["Tax or Benefits File", "A work-related tax, benefit, pension, insurance, leave, or employment-benefit file."],
    ["Company ID or Badge", "A workplace, company, guild, agency, or organisation identification record."],
    ["Union or Guild Record", "A record of union, guild, professional body, or work-organisation membership."],
    ["Workplace Incident File", "A file about a workplace incident, accident, complaint, conflict, disciplinary process, or safety event. The file does not by itself prove fault."],
    ["Termination or Resignation File", "A record about leaving a role through termination, resignation, dismissal, retirement, contract ending, or transfer."],
    ["Agency Contract", "A contract with or through an agency, manager, guild, broker, or representative."],
    ["Character Workplace File", "A fictional-character file about workplace, company, role, guild, contract, rank, mission, or career story details."],
    ["Other Work or Company File", "A work or company file not represented by the listed choices; record the source wording and what it contains."]
  ]),
  ...category("Families and relationships", [
    ["Nuclear family", "A family group consisting of parent or parents and their children."],
    ["Immediate family", "Someone's closest family group, often parents, children, siblings, and a spouse or partner. The exact group depends on context."],
    ["Extended family", "Relatives beyond the closest family group, such as grandparents, aunts, uncles, and cousins."],
    ["Stepfamily", "A family where a parent has a spouse or partner who is not the child's other parent."],
    ["Blended family", "A family formed when partners bring children from earlier relationships together, sometimes with children they have together."],
    ["Foster family", "A family providing care for a child through a foster arrangement. Fostering does not itself create an adoptive relationship.", [], ["fostering"]],
    ["Adoptive family", "A family connected through adoption."],
    ["Biological family", "Family connected through birth or genetic parentage, as supported by the records."],
    ["Single-parent family", "A family in which one parent is raising a child or children. This does not by itself describe legal custody."],
    ["In-law family", "Family connections formed through marriage, such as a spouse's parents or a child's spouse."],
    ["Chosen family", "People someone regards as family through close bonds and commitment, whether or not they share ancestry or legal ties."],
    ["Household family", "People grouped as family because they share a home. Living together does not by itself prove ancestry or marriage."],
    ["Guardianship family", "A family group in which a guardian has recorded responsibility for someone's care. It does not automatically mean adoption."],
    ["Biological relative", "A relative connected through recorded birth or genetic parentage.", ["Biological"]],
    ["Adoptive relative", "A relative connected through adoption.", ["Adoptive"]],
    ["Foster relative", "A family connection formed through foster care, such as a foster parent or foster sibling."],
    ["Step relative", "A family connection through a parent's later spouse or partner rather than shared parentage.", ["Step"]],
    ["Half sibling", "A sibling who shares one biological parent with you.", ["Half brother", "Half sister"]],
    ["Step sibling", "A child of your stepparent who does not share a parent with you through that step relationship.", ["Stepbrother", "Stepsister"]],
    ["Foster sibling", "Another child in the same foster family, connected through that care arrangement."],
    ["Adoptive sibling", "A sibling connected through adoption into the same family."],
    ["In-law", "A relative connected through marriage. The exact connection should be named."],
    ["Mother-in-law", "Your spouse's mother."],
    ["Father-in-law", "Your spouse's father."],
    ["Sister-in-law", "Your spouse's sister or your sibling's wife. Some families also use it for a spouse's sibling's wife."],
    ["Brother-in-law", "Your spouse's brother or your sibling's husband. Some families also use it for a spouse's sibling's husband."],
    ["Child-in-law", "The spouse of your child.", ["Son-in-law", "Daughter-in-law"]],
    ["Cousin-in-law", "Your cousin's spouse or your spouse's cousin. Marriage creates this connection; it does not add a generation of cousin removal."],
    ["Godparent", "Someone named to support a child's religious or personal upbringing. The role alone does not make them a legal guardian."],
    ["Godchild", "A person for whom someone has taken on the role of godparent."],
    ["Household member", "A person living in the same home. They need not be a relative."],
    ["Caregiver", "Someone who helps with another person's care or daily needs. Providing care does not by itself give legal custody.", ["Carer"]],
    ["Parent", "Someone recorded as a person's parent. The parentage type can be biological, adoptive, foster, step, or unspecified."],
    ["Child", "Someone recorded as another person's child, regardless of their current age."],
    ["Parent-child", "A recorded link from a parent to a child. The parentage type gives further detail about that link."],
    ["Mother", "A parent recorded in the mother role. The role alone does not specify biological or adoptive parentage."],
    ["Father", "A parent recorded in the father role. The role alone does not specify biological or adoptive parentage."],
    ["Sibling", "A brother, sister, or other person recorded as sharing a parent relationship. A sibling label alone does not specify full, half, or adoptive status."],
    ["Spouse", "A person to whom someone is married. A recorded spouse link may describe a current or former marriage."],
    ["Husband", "A spouse recorded with the husband label. This describes the relationship role, not whether the marriage is current, former, civil, religious, or legally recognised everywhere."],
    ["Wife", "A spouse recorded with the wife label. This describes the relationship role, not whether the marriage is current, former, civil, religious, or legally recognised everywhere."],
    ["Partner", "Someone recorded as being in a couple relationship. This label alone does not establish marriage or another legal status."],
    ["Fiance", "A person recorded as engaged to marry. This spelling is often used without accents; the record should keep the person's or source's wording.", ["Fiancee"]],
    ["Engaged partner", "A partner recorded as being engaged or intending to marry. Engagement does not prove a marriage later happened."],
    ["Dating partner", "A partner recorded as dating. Dating does not by itself establish marriage, cohabitation, custody, or legal status."],
    ["Boyfriend", "A partner recorded with the boyfriend label. The label should come from the person's own wording or a source."],
    ["Girlfriend", "A partner recorded with the girlfriend label. The label should come from the person's own wording or a source."],
    ["Life partner", "A long-term or committed partner recorded with life-partner wording. It does not automatically establish marriage or legal status."],
    ["Domestic partner", "A partner recorded in a domestic partnership or domestic-partner relationship. Legal meaning depends on place and date."],
    ["Civil union partner", "A partner recorded in a civil union. Rights and recognition depend on the civil-union law that applies."],
    ["Common-law partner", "A partner recorded as common-law or marriage-like. Legal recognition varies by jurisdiction and time."],
    ["Polyamorous partner", "A partner in a consensual relationship structure where someone may have more than one romantic, intimate, or committed partner. It should be recorded only from the people's own wording or a source."],
    ["Multiple partner relationship", "A relationship record involving more than two partners. Record consent, roles, dates, and the people's own wording instead of assuming a legal or romantic status."],
    ["Polycule member", "A person recorded as part of a polycule, meaning a connected network of consensual non-monogamous relationships."],
    ["Former spouse", "A person who was previously recorded as a spouse. The end reason may be divorce, annulment, death, separation, or another record."],
    ["Former partner", "A person who was previously recorded as a partner. The label does not state why the relationship ended."],
    ["Separated spouse", "A spouse recorded as separated. Separation is not the same as a completed divorce unless the legal record says so."],
    ["Annulled spouse", "A spouse connected to a marriage that was annulled. The record should state whether the annulment was civil, religious, or both."],
    ["Co-parent", "Someone recorded as sharing a parenting role. A co-parent link does not automatically mean a romantic relationship, marriage, or custody order."],
    ["Ex-partner", "A former partner recorded with ex-partner wording. The label does not state the relationship type or reason it ended."],
    ["Guardian", "Someone with recorded legal authority to care for another person or make specified decisions for them. The order or record defines that authority."],
    ["Ward", "A person placed under a guardian's or court's protection or care. The record determines the scope of that arrangement."],
    ["Relative", "Someone connected through family relationships. The particular connection should be recorded."],
    ["Parentage", "The kind of parent-child connection recorded, such as biological or adoptive. An unspecified link must not be assumed biological."],
    ["Unspecified", "The type or detail has not been recorded. It is not a claim that a particular type applies."],
    ["Widowed", "A person whose spouse has died. The record's date matters when describing their later relationship status."],
    ["Single mom", "A mother raising a child or children as a single parent. The label does not establish custody or marital status.", ["Single mother"]],
    ["Single dad", "A father raising a child or children as a single parent. The label does not establish custody or marital status.", ["Single father"]]
  ]),
  ...category("Kinship", [
    ["Kinship", "How people are connected through family relationships. KinForge describes the links recorded in the tree, not proof of genetic relatedness."],
    ["Ancestor", "A parent, grandparent, or someone further back along a line of parents.", ["Ancestors"]],
    ["Descendant", "A child, grandchild, or someone further down a line of children.", ["Descendants", "Descendancy"]],
    ["Grandparent", "A parent of one of your parents."],
    ["Grandchild", "A child of one of your children."],
    ["Aunt or uncle", "A sibling of one of your parents. These words can also be used for that person's spouse or a close family friend; the recorded path explains which.", ["Aunt", "Uncle"]],
    ["Niece or nephew", "A child of your sibling. Family usage may also include a spouse's sibling's child.", ["Niece", "Nephew"]],
    ["Cousin", "A relative reached through a shared ancestor on a different branch, rather than a direct ancestor, descendant, or sibling. The cousin number and removal explain the connection."],
    ["First cousin", "Someone whose parent is your parent's sibling. You share a grandparent and are in the same family generation.", ["1st cousin"]],
    ["Second cousin", "Someone who shares a great-grandparent with you, with both of you the same number of generations below that ancestor.", ["2nd cousin"]],
    ["Third cousin", "Someone who shares a great-great-grandparent with you, with both of you the same number of generations below that ancestor.", ["3rd cousin"]],
    ["Removed", "For cousins, the number of generations between their positions in the family tree. It is not their age difference or a marriage connection.", ["Cousin removal"]],
    ["Once removed", "One family generation apart. Your first cousin's child, or your parent's first cousin, is your first cousin once removed.", ["First cousin once removed", "1st cousin once removed"]],
    ["Twice removed", "Two family generations apart. Your first cousin's grandchild is your first cousin twice removed.", ["First cousin twice removed", "1st cousin twice removed"]],
    ["Thrice removed", "Three family generations apart. Your first cousin's great-grandchild is your first cousin three times removed.", ["Three times removed", "First cousin thrice removed", "First cousin three times removed", "1st cousin three times removed"]],
    ["Generation", "One step between a parent and child in a family line. Family generations are based on relationships, not on people's ages."],
    ["Common ancestor", "An ancestor shared by two people through their recorded parent-child links.", ["Shared ancestor"]],
    ["Maternal", "Through the parent recorded as the mother. KinForge uses the recorded role, not a guess from a name or gender."],
    ["Paternal", "Through the parent recorded as the father. KinForge uses the recorded role, not a guess from a name or gender."],
    ["Side not recorded", "The first parent's role on this family path has not been recorded, so a maternal or paternal side cannot be named."],
    ["Reference person", "The person from whose point of view a chart or relationship report is described.", ["Focus person"]],
    ["Comparison person", "The other person whose connection to the reference person is being examined."],
    ["Relationship path", "The sequence of recorded people and links connecting two people in the tree."],
    ["Pedigree", "A person's ancestry shown as a list or family tree."],
    ["Pedigree collapse", "When the same ancestor appears along more than one family branch, so there are fewer different ancestors than separate chart positions.", ["Repeated ancestor"]],
    ["Ancestry cycle", "A mistake in the recorded links that makes someone their own ancestor. This is different from one ancestor appearing on several branches.", ["Parent-child cycle"]]
  ]),
  ...category("Burial and remembrance", [
    ["Burial", "Placing a person's body or remains in a grave or other resting place."],
    ["Cremation", "Reducing a deceased person's body to cremated remains, often called ashes, using intense heat."],
    ["Cemetery interment", "Placing a body or cremated remains in a cemetery grave, tomb, or other burial space.", ["Interment"]],
    ["Mausoleum", "A building or structure containing tombs, usually above ground."],
    ["Columbarium", "A structure with small spaces, called niches, for urns containing cremated remains."],
    ["Memorial", "An event, object, page, or place created to remember someone who has died."],
    ["Memorial only", "A remembrance site or record without a burial or placement of remains recorded there."],
    ["Scattering", "Spreading cremated remains at a chosen location."],
    ["Green burial", "Burial intended to reduce environmental impact, often using biodegradable materials and avoiding embalming. Practices vary."],
    ["Reburial", "Moving remains from an earlier resting place and burying them again elsewhere."],
    ["Burial date", "The date remains were buried or placed in their resting place. It may differ from the date of death."],
    ["Burial site", "The location where a person's remains were placed."],
    ["Cemetery", "A place set aside for burials or the keeping of remains.", ["Cemetery name"]],
    ["Cemetery address", "The street address or location description of the cemetery."],
    ["Cemetery plot", "A particular burial space or section in a cemetery.", ["Plot"]],
    ["Grave number", "The number or reference used to locate a particular grave."],
    ["Gravestone", "A marker at a grave, often bearing a name and dates.", ["Headstone"]],
    ["Gravestone inscription", "The words or symbols written on a grave marker."],
    ["Memorial URL", "The web address of a page remembering the person."],
    ["Funeral home", "A business or service that helps arrange care of the deceased and funeral ceremonies."],
    ["Death place", "The place where a person died, which may differ from their home or burial place."],
    ["Death hospital", "The hospital recorded as the place of death, if applicable."],
    ["Death address", "The address recorded for the location where a person died."],
    ["Death and burial notes", "Additional source details about a person's death, funeral, or resting place."]
  ]),
  ...category("Charts", [
    ["Tree Chart", "A diagram showing people and the recorded family links between them."],
    ["Hourglass Chart", "A family chart showing both ancestors and descendants around a focus person."],
    ["Ancestor Chart", "A chart tracing parents, grandparents, and earlier generations back from a person."],
    ["Double Ancestor Chart", "A chart comparing two sets of ancestors, commonly those of a couple."],
    ["Fan Chart", "An ancestor chart shaped like a fan, with earlier generations arranged in widening bands."],
    ["Descendant Chart", "A chart tracing a person's children, grandchildren, and later generations."],
    ["Timeline", "Events placed in date order so you can see when things happened.", ["Timeline Chart"]],
    ["Statistics Chart", "A chart summarising counts or patterns in the recorded data, such as births by year."],
    ["Relationship Chart", "A diagram showing the recorded links connecting people."],
    ["Genogram Chart", "A family diagram using symbols and lines to show recorded relationships and personal information. Symbols do not establish a diagnosis.", ["Genogram"]],
    ["Sociogram", "A diagram of recorded social or family connections between people."],
    ["Fractal Ancestor HV Tree", "An ancestor chart whose branches alternate between horizontal and vertical directions. HV means horizontal and vertical."],
    ["Fractal Symmetrical Tree", "A family chart using repeating, balanced branch shapes to arrange generations."],
    ["Fractal Circular Tree", "A family chart using a repeating branching pattern arranged around a circle."],
    ["Fractal Ancestor Tree Chart", "An ancestor chart that repeats a branching pattern to fit successive generations."],
    ["Name Distribution", "A summary of how often family names (surnames) occur among the people in the tree.", ["Name Distribution Chart"]],
    ["Ahnentafel", "A numbered ancestor list: the focus person is 1, with parent positions at twice a person's number and twice that number plus 1. Missing or repeated ancestors keep their own positions.", ["Ahnentafel Diagram"]],
    ["Pedigree map", "A map of places associated with people and events in a family tree.", ["PedigreeMap"]],
    ["Branch", "A line or group of related people within a larger family tree."],
    ["Glyph", "A small symbol that stands for an event, relationship, or recorded detail.", ["Symbol"]],
    ["Legend", "A key explaining the symbols, colours, or line styles in a chart.", ["Symbol legend"]]
  ]),
  ...category("Reports and lists", [
    ["Person Report", "A summary of one person's recorded life, family, events, and sources."],
    ["Person Events Report", "A report of the events recorded for one person."],
    ["Family Group Report", "A report bringing together the people, children, and details recorded for one family group."],
    ["Kinship Report", "A report explaining how people are related through the links recorded in the tree."],
    ["Map Report", "A report showing recorded family places on a map."],
    ["Story Report", "A written account of family history using the saved people, events, and notes."],
    ["World History Report", "A report placing recorded family events alongside wider historical events."],
    ["Narrative Report", "A report written in sentences and paragraphs from the recorded family information."],
    ["Ahnentafel Report", "A report listing a person's ancestors in numbered parent positions."],
    ["Descendancy Report", "A report following a person's children and later generations."],
    ["Register Report", "A numbered account of descendants, organised by generation so family groups can be followed."],
    ["Status Report", "A summary of the tree's records, missing details, and research progress."],
    ["Timeline Report", "A report listing recorded events in date order."],
    ["Today Report", "A report of recorded anniversaries that fall on today's day and month."],
    ["Family Tree Book", "A collection of family-history chapters and reports prepared together as a book."],
    ["Medical Files Report", "A report listing medical, diagnosis, treatment, prescription, therapy, assessment, and accessibility files linked to people in the tree."],
    ["Diagnosis Files Report", "A report focused on diagnosis records, diagnosis dates, diagnostic criteria, clinicians, and attached diagnosis files."],
    ["Prescription Files Report", "A report focused on prescription records and medication-related documents. It records history and is not medication advice."],
    ["Treatment Files Report", "A report focused on treatment plans, therapy records, procedures, hospital visits, and care plans."],
    ["Work Contracts Report", "A report listing work contracts, employment agreements, freelance contracts, and workplace files for people or fictional characters."],
    ["Company Files Report", "A report listing company, employment, workplace, role, payroll, accommodation, or organisation files."],
    ["Character Work Files Report", "A report focused on fictional-character career, company, guild, workplace, and contract records."],
    ["Family Report", "A summary of a family's recorded members, relationships, and events."],
    ["Particularities Report", "A report of distinctive recorded personal facts and details."],
    ["Person Analysis", "A review of a person's recorded dates, facts, and relationships to identify gaps or possible inconsistencies."],
    ["Plausibility Report", "A list of details that may need checking, such as a child born before a parent's birth. A warning is not proof that a record is wrong."],
    ["Sources List", "A list of the documents and other evidence saved for the tree."],
    ["Descendancy List", "A list of a person's children, grandchildren, and later generations."],
    ["Marriage List", "A list of the recorded marriages and their details.", ["Marriages List"]],
    ["Places List", "A list of saved locations associated with people, events, or sources."],
    ["Events List", "A list of recorded life events, such as births, moves, and marriages."],
    ["Anniversary List", "A list of recurring calendar dates for recorded events, such as birthdays and wedding anniversaries."],
    ["Name Distribution Report", "A report counting the occurrences of family names (surnames) in the tree."],
    ["Influential People Report", "A report highlighting people by their recorded connections in the tree. Connection counts are not a measure of someone's worth or historical importance."],
    ["Facts List", "A list of saved personal details, such as occupations, languages, and physical descriptions."],
    ["Distinctive Persons List", "A list highlighting people with distinctive details recorded in the tree."],
    ["Persons List", "A list of the people recorded in the tree."],
    ["ToDo List", "A list of research or editing tasks waiting to be completed."],
    ["LDS Ordinances List", "A list of recorded Latter-day Saint religious ceremonies associated with people in the tree."],
    ["Changes List", "A history of recorded edits to the family-tree data."]
  ]),
  ...category("Records and app terms", [
    ["Genealogy", "The study and recording of family history and relationships."],
    ["Source", "Where information came from, such as a certificate, interview, book, or archive."],
    ["Citation", "Details identifying a source and the particular page, item, or passage supporting a statement."],
    ["Repository", "The place or organisation that holds a source, such as an archive or library."],
    ["Record", "A saved account or document containing information about a person, event, or family."],
    ["Fact", "A saved personal detail, such as an occupation or height. Calling it a fact in the app does not prove the information is correct."],
    ["Event", "Something that happened in a person's or family's history, usually associated with a date or place."],
    ["Evidence", "Information used to support or question a family-history claim."],
    ["Transcription", "A written copy of the wording in an original document."],
    ["GEDCOM", "A file format used to exchange family-tree records between genealogy programs. Programs may support different details."],
    ["Media", "Saved images, documents, recordings, and other files connected to the tree."],
    ["Collection", "A group used to organise related trees or records."],
    ["Book", "A named group of family-history material. A printed family tree book is a separate report output."],
    ["Backup", "A saved copy of data that can be used to restore it later."],
    ["Import", "Bringing data from a file or another source into the app."],
    ["Export", "Creating a file containing selected data so it can be kept or used elsewhere."],
    ["Merge", "Combining records believed to describe the same person or item. Conflicting details need review."],
    ["Duplicate", "A second record that may describe the same person or item as another record."],
    ["Private", "Marked as sensitive or restricted in the app. Inclusion in a particular report or export depends on that output's settings."],
    ["Latitude", "A location's position north or south of the equator, measured in degrees."],
    ["Longitude", "A location's position east or west of the prime meridian, measured in degrees."],
    ["Approximate date", "An estimated date rather than an exact one, often written as about or circa.", ["Circa"]],
    ["Unknown", "The answer is not known from the available information. It does not mean the event did not happen."],
    ["Not recorded", "No value has been entered for this detail. This does not establish that there was none.", ["None recorded"]],
    ["Other", "A recorded type outside the named options. Its specific meaning must be explained in the accompanying details."],
    ["Associated", "Linked to the named service or organisation in the record, without specifying whether participation is current."],
    ["Active", "Marked as currently ongoing at the time the status was recorded."],
    ["Former", "A relationship, role, or service connection that applied in the past."],
    ["Custom term", "A label added by a user. Its meaning comes from their notes or source; the glossary cannot assume a definition."]
  ])
].sort((a, b) => a.term.localeCompare(b.term, "en"));

function normalise(value: string): string {
  return value.normalize("NFKD").replace(/\p{M}/gu, "").toLowerCase().replace(/[-\u2010-\u2015]/g, " ").replace(/\s+/g, " ").trim();
}

const entriesByTerm = new Map(GLOSSARY_ENTRIES.flatMap(entry => [entry.term, ...entry.aliases].map(term => [normalise(term), entry] as const)));

/** Exact, case-insensitive lookup; an unfamiliar custom label has no guessed meaning. */
export function meaningFor(term: string): string | undefined {
  return entriesByTerm.get(normalise(term))?.meaning;
}

export function searchTerms(query: string, additionalEntries: readonly GlossaryEntry[] = []): GlossaryEntry[] {
  const normalisedQuery = normalise(query);
  const words = normalisedQuery.split(" ").filter(Boolean);
  const entries = [...GLOSSARY_ENTRIES, ...additionalEntries];
  const tokens = (entry: GlossaryEntry) => normalise([entry.term, ...entry.aliases, entry.meaning, entry.category].join(" ")).split(" ").filter(Boolean);
  const matchesWord = (word: string, entry: GlossaryEntry) => tokens(entry).some(token => token === word || (word.length > 4 && token.includes(word)));
  const rank = (entry: GlossaryEntry) => {
    const label = normalise(entry.term);
    if (label === normalisedQuery || entry.aliases.some(alias => normalise(alias) === normalisedQuery)) return 0;
    if (label.startsWith(normalisedQuery)) return 1;
    if (words.every(word => normalise([entry.term, ...entry.aliases].join(" ")).includes(word))) return 2;
    return 3;
  };
  return entries.filter(entry => {
    return words.every(word => matchesWord(word, entry));
  }).sort((a, b) => rank(a) - rank(b));
}
